import json
from generate_social_data import make_social_file

g6_lessons = [
  # វិច្ឆិកា (Nov)
  {
    "id": "soc_g6_w03_01",
    "weekNumber": 3,
    "monthKm": "វិច្ឆិកា",
    "subjectId": "sub_social",
    "chapterKm": "រំលឹកឡើងវិញ",
    "lessonTitleKm": "រំលឹកឡើងវិញមេរៀនសិក្សាសង្គម ថ្នាក់ទី៥ (សប្តាហ៍ទី៣)",
    "lessonTitleEn": "Revision of Grade 5 Social Studies (Week 3)",
    "objectivesKm": "រំលឹកឡើងវិញនូវមូលដ្ឋានគ្រឹះនៃមុខវិជ្ជាសិក្សាសង្គមថ្នាក់ទី៥",
    "hoursCount": 4,
    "semester": 1,
    "status": "completed",
    "pageSs": "1",
    "notes": "រំលឹកឡើងវិញ"
  },
  {
    "id": "soc_g6_w04_01",
    "weekNumber": 4,
    "monthKm": "វិច្ឆិកា",
    "subjectId": "sub_social",
    "chapterKm": "រំលឹកឡើងវិញ",
    "lessonTitleKm": "រំលឹកឡើងវិញមេរៀនសិក្សាសង្គម ថ្នាក់ទី៥ (សប្តាហ៍ទី៤)",
    "lessonTitleEn": "Revision of Grade 5 Social Studies (Week 4)",
    "objectivesKm": "ពង្រឹងចំណេះដឹងត្រៀមចូលមេរៀនថ្នាក់ទី៦",
    "hoursCount": 4,
    "semester": 1,
    "status": "completed",
    "pageSs": "1",
    "notes": "រំលឹកឡើងវិញ"
  },

  # ធ្នូ (Dec)
  {
    "id": "soc_g6_w05_01",
    "weekNumber": 5,
    "monthKm": "ធ្នូ",
    "subjectId": "sub_social",
    "chapterKm": "ជំពូកទី ១ សីលធម៌ និងពលរដ្ឋវិជ្ជា",
    "lessonTitleKm": "មេរៀនទី ១ ការទទួលខុសត្រូវ (ក. លើខ្លួនឯង និងគ្រួសារ)",
    "lessonTitleEn": "Chapter 1 Lesson 1: Responsibility - Towards Self & Family",
    "objectivesKm": "យល់ដឹងពីទំនួលខុសត្រូវផ្ទាល់ខ្លួន ការសិក្សា និងការជួយការងារគ្រួសារ",
    "hoursCount": 4,
    "semester": 1,
    "status": "completed",
    "pageSs": "2-5"
  },
  {
    "id": "soc_g6_w06_01",
    "weekNumber": 6,
    "monthKm": "ធ្នូ",
    "subjectId": "sub_social",
    "chapterKm": "ជំពូកទី ១ សីលធម៌ និងពលរដ្ឋវិជ្ជា",
    "lessonTitleKm": "មេរៀនទី ១ ការទទួលខុសត្រូវ (ខ. ចំពោះសាលារៀន និងសង្គមជាតិ)",
    "lessonTitleEn": "Lesson 1: Responsibility - School Community & Nation",
    "objectivesKm": "បង្ហាញពីស្មារតីទទួលខុសត្រូវចំពោះសាលារៀន សង្គម និងការគោរពច្បាប់",
    "hoursCount": 4,
    "semester": 1,
    "status": "completed",
    "pageSs": "6-9"
  },
  {
    "id": "soc_g6_w07_01",
    "weekNumber": 7,
    "monthKm": "ធ្នូ",
    "subjectId": "sub_social",
    "chapterKm": "ជំពូកទី ១ សីលធម៌ និងពលរដ្ឋវិជ្ជា",
    "lessonTitleKm": "មេរៀនទី ២ លទ្ធិប្រជាធិបតេយ្យ និងសិទ្ធិមនុស្ស (ក. អត្ថន័យប្រជាធិបតេយ្យ)",
    "lessonTitleEn": "Lesson 2: Democracy & Human Rights - Meaning of Democracy",
    "objectivesKm": "ពន្យល់ពីអត្ថន័យនៃលទ្ធិប្រជាធិបតេយ្យ និងការបោះឆ្នោត",
    "hoursCount": 4,
    "semester": 1,
    "status": "completed",
    "pageSs": "12-15"
  },
  {
    "id": "soc_g6_w08_01",
    "weekNumber": 8,
    "monthKm": "ធ្នូ",
    "subjectId": "sub_social",
    "chapterKm": "ជំពូកទី ១ សីលធម៌ និងពលរដ្ឋវិជ្ជា",
    "lessonTitleKm": "មេរៀនទី ២ លទ្ធិប្រជាធិបតេយ្យ និងសិទ្ធិមនុស្ស (ខ. សេចក្តីប្រកាសជាសកលស្តីពីសិទ្ធិមនុស្ស)",
    "lessonTitleEn": "Lesson 2: Universal Declaration of Human Rights (UDHR)",
    "objectivesKm": "យល់ដឹងពីសេចក្តីប្រកាសជាសកលស្តីពីសិទ្ធិមនុស្ស និងសេរីភាពជាមូលដ្ឋាន",
    "hoursCount": 4,
    "semester": 1,
    "status": "completed",
    "pageSs": "16-19"
  },

  # មករា (Jan)
  {
    "id": "soc_g6_w09_01",
    "weekNumber": 9,
    "monthKm": "មករា",
    "subjectId": "sub_social",
    "chapterKm": "ជំពូកទី ១ សីលធម៌ និងពលរដ្ឋវិជ្ជា",
    "lessonTitleKm": "មេរៀនទី ៣ យេនឌ័រ និងសមភាពសង្គម (ក. គំនិតយេនឌ័រ)",
    "lessonTitleEn": "Lesson 3: Gender & Social Equality - Gender Concepts",
    "objectivesKm": "បែងចែកភាពខុសគ្នារវាងភេទ និងយេនឌ័រ និងការលុបបំបាត់ការរើសអើង",
    "hoursCount": 4,
    "semester": 1,
    "status": "completed",
    "pageSs": "22-25"
  },
  {
    "id": "soc_g6_w10_01",
    "weekNumber": 10,
    "monthKm": "មករា",
    "subjectId": "sub_social",
    "chapterKm": "ជំពូកទី ១ សីលធម៌ និងពលរដ្ឋវិជ្ជា",
    "lessonTitleKm": "មេរៀនទី ៣ យេនឌ័រ និងសមភាពសង្គម (ខ. សមភាពយេនឌ័រក្នុងការអភិវឌ្ឍ)",
    "lessonTitleEn": "Lesson 3: Gender Equality in Development & Leadership",
    "objectivesKm": "បង្ហាញពីសារៈសំខាន់នៃសមភាពយេនឌ័រក្នុងភាពជាអ្នកដឹកនាំ និងការអភិវឌ្ឍសង្គម",
    "hoursCount": 4,
    "semester": 1,
    "status": "completed",
    "pageSs": "26-29"
  },
  {
    "id": "soc_g6_w11_01",
    "weekNumber": 11,
    "monthKm": "មករា",
    "subjectId": "sub_social",
    "chapterKm": "ជំពូកទី ២ សុវត្ថិភាពសង្គម និងការយល់ដឹងពីច្បាប់",
    "lessonTitleKm": "មេរៀនទី ១ ច្បាប់ចរាចរណ៍ផ្លូវគោក (ក. វិធាននៃការបើកបរ)",
    "lessonTitleEn": "Chapter 2 Lesson 1: Road Traffic Law - Driving Rules & Speed",
    "objectivesKm": "យល់ដឹងពីល្បឿនកំណត់ ការបត់ ការជែង និងការគោរពសិទ្ធិអាទិភាព",
    "hoursCount": 4,
    "semester": 1,
    "status": "completed",
    "pageSs": "32-35"
  },
  {
    "id": "soc_g6_w12_01",
    "weekNumber": 12,
    "monthKm": "មករា",
    "subjectId": "sub_social",
    "chapterKm": "ជំពូកទី ២ សុវត្ថិភាពសង្គម និងការយល់ដឹងពីច្បាប់",
    "lessonTitleKm": "មេរៀនទី ១ ច្បាប់ចរាចរណ៍ផ្លូវគោក (ខ. ការពិន័យ និងការការពារគ្រោះថ្នាក់)",
    "lessonTitleEn": "Lesson 1: Traffic Penalties & Accident Prevention",
    "objectivesKm": "យល់ដឹងពីទោសទណ្ឌនៃការបំពានច្បាប់ចរាចរណ៍ និងវិធានការការពារគ្រោះថ្នាក់",
    "hoursCount": 4,
    "semester": 1,
    "status": "completed",
    "pageSs": "36-39"
  },

  # កុម្ភៈ (Feb)
  {
    "id": "soc_g6_w13_01",
    "weekNumber": 13,
    "monthKm": "កុម្ភៈ",
    "subjectId": "sub_social",
    "chapterKm": "ជំពូកទី ២ សុវត្ថិភាពសង្គម និងការយល់ដឹងពីច្បាប់",
    "lessonTitleKm": "មេរៀនទី ២ ការទប់ស្កាត់គ្រឿងញៀន និងអំពើហិង្សា (ក. គ្រោះថ្នាក់នៃគ្រឿងញៀន)",
    "lessonTitleEn": "Lesson 2: Drug Prevention & Anti-Violence - Dangers of Drugs",
    "objectivesKm": "ស្គាល់ផលប៉ះពាល់ធ្ងន់ធ្ងរនៃគ្រឿងញៀនចំពោះសុខភាព គ្រួសារ និងសង្គម",
    "hoursCount": 4,
    "semester": 1,
    "status": "in_progress",
    "pageSs": "42-45"
  },
  {
    "id": "soc_g6_w14_01",
    "weekNumber": 14,
    "monthKm": "កុម្ភៈ",
    "subjectId": "sub_social",
    "chapterKm": "ជំពូកទី ២ សុវត្ថិភាពសង្គម និងការយល់ដឹងពីច្បាប់",
    "lessonTitleKm": "មេរៀនទី ២ ការទប់ស្កាត់គ្រឿងញៀន និងអំពើហិង្សា (ខ. ការទប់ស្កាត់អំពើហិង្សាក្នុងគ្រួសារ)",
    "lessonTitleEn": "Lesson 2: Preventing Domestic Violence & Bullying",
    "objectivesKm": "ចូលរួមទប់ស្កាត់អំពើហិង្សាក្នុងគ្រួសារ និងការសម្លុតធ្វើបាបក្នុងសាលារៀន",
    "hoursCount": 4,
    "semester": 1,
    "status": "in_progress",
    "pageSs": "46-49"
  },
  {
    "id": "soc_g6_w15_01",
    "weekNumber": 15,
    "monthKm": "កុម្ភៈ",
    "subjectId": "sub_social",
    "chapterKm": "ជំពូកទី ៣ ប្រវត្តិវិទ្យា (ប្រវត្តិសាស្ត្រខ្មែរ)",
    "lessonTitleKm": "មេរៀនទី ១ ប្រទេសកម្ពុជាសម័យកណ្តាល (ក. សម័យចតុមុខ និងលង្វែក)",
    "lessonTitleEn": "Chapter 3 Lesson 1: Post-Angkorian Era - Chaktomuk & Longvek Periods",
    "objectivesKm": "ពណ៌នាអំពីការផ្លាស់ប្តូររាជធានីមករាជធានីចតុមុខ និងភាពរុងរឿងនៃសម័យលង្វែក",
    "hoursCount": 4,
    "semester": 1,
    "status": "in_progress",
    "pageSs": "52-55"
  },
  {
    "id": "soc_g6_w16_01",
    "weekNumber": 16,
    "monthKm": "កុម្ភៈ",
    "subjectId": "sub_social",
    "chapterKm": "ជំពូកទី ៣ ប្រវត្តិវិទ្យា (ប្រវត្តិសាស្ត្រខ្មែរ)",
    "lessonTitleKm": "មេរៀនទី ១ ប្រទេសកម្ពុជាសម័យកណ្តាល (ខ. សម័យឧដុង្គ)",
    "lessonTitleEn": "Lesson 1: Oudong Period - Culture & Monarchy",
    "objectivesKm": "រៀបរាប់ពីប្រវត្តិសាស្ត្រសម័យឧដុង្គ វប្បធម៌ និងការដឹកនាំប្រទេស",
    "hoursCount": 4,
    "semester": 1,
    "status": "in_progress",
    "pageSs": "56-59"
  },

  # មីនា (Mar)
  {
    "id": "soc_g6_w17_01",
    "weekNumber": 17,
    "monthKm": "មីនា",
    "subjectId": "sub_social",
    "chapterKm": "ជំពូកទី ៣ ប្រវត្តិវិទ្យា (ប្រវត្តិសាស្ត្រខ្មែរ)",
    "lessonTitleKm": "មេរៀនទី ២ សម័យអាណានិគមនិយមបារាំង (ក. កម្ពុជាក្រោមអាណាព្យាបាលបារាំង)",
    "lessonTitleEn": "Lesson 2: French Protectorate of Cambodia - Historical Background",
    "objectivesKm": "ពន្យល់ពីកិច្ចព្រមព្រៀងអាណាព្យាបាលបារាំងឆ្នាំ១៨៦៣ និងការកែទម្រង់រដ្ឋបាល",
    "hoursCount": 4,
    "semester": 1,
    "status": "upcoming",
    "pageSs": "62-65"
  },
  {
    "id": "soc_g6_w18_01",
    "weekNumber": 18,
    "monthKm": "មីនា",
    "subjectId": "sub_social",
    "chapterKm": "ជំពូកទី ៣ ប្រវត្តិវិទ្យា (ប្រវត្តិសាស្ត្រខ្មែរ)",
    "lessonTitleKm": "មេរៀនទី ២ សម័យអាណានិគមបារាំង (ខ. ចលនាតស៊ូដើម្បីឯករាជ្យ & ប្រឡងឆមាសទី១)",
    "lessonTitleEn": "Lesson 2: Independence Struggle Movement & Semester 1 Examination",
    "objectivesKm": "ពណ៌នាអំពីចលនាតស៊ូដណ្តើមឯករាជ្យ ព្រះរាជបូชนីយកិច្ច និងប្រឡងឆមាសទី១",
    "hoursCount": 4,
    "semester": 1,
    "status": "upcoming",
    "isExamOrHoliday": True,
    "pageSs": "66-69",
    "notes": "ប្រឡងឆមាសទី១"
  },

  # Semester 2
  {
    "id": "soc_g6_w19_01",
    "weekNumber": 19,
    "monthKm": "មីនា",
    "subjectId": "sub_social",
    "chapterKm": "ជំពូកទី ៣ ប្រវត្តិវិទ្យា (ប្រវត្តិសាស្ត្រខ្មែរ)",
    "lessonTitleKm": "មេរៀនទី ៣ ព្រះរាជាណាចក្រកម្ពុជាសម័យសង្គមរាស្ត្រនិយម",
    "lessonTitleEn": "Lesson 3: Sangkum Reastr Niyum Era - Golden Era of Development",
    "objectivesKm": "បង្ហាញពីសមិទ្ធផលលេចធ្លោលើវិស័យអប់រំ កសិកម្ម និងហេដ្ឋារចនាសម្ព័ន្ធសម័យសង្គមរាស្ត្រនិយម",
    "hoursCount": 4,
    "semester": 2,
    "status": "upcoming",
    "pageSs": "72-75"
  },
  {
    "id": "soc_g6_w20_01",
    "weekNumber": 20,
    "monthKm": "មីនា",
    "subjectId": "sub_social",
    "chapterKm": "ជំពូកទី ៣ ប្រវត្តិវិទ្យា (ប្រវត្តិសាស្ត្រខ្មែរ)",
    "lessonTitleKm": "មេរៀនទី ៤ កម្ពុជាសម័យទំនើប និងសន្តិភាពពេញលេញ (នយោបាយឈ្នះ-ឈ្នះ)",
    "lessonTitleEn": "Lesson 4: Modern Cambodia & Win-Win Policy for Complete Peace",
    "objectivesKm": "យល់ដឹងពីដំណើរការស្វែងរកសន្តិភាព នយោបាយឈ្នះ-ឈ្នះ និងការអភិវឌ្ឍជាតិបច្ចុប្បន្ន",
    "hoursCount": 4,
    "semester": 2,
    "status": "upcoming",
    "pageSs": "76-79"
  },

  # មេសា (Apr)
  {
    "id": "soc_g6_w21_01",
    "weekNumber": 21,
    "monthKm": "មេសា",
    "subjectId": "sub_social",
    "chapterKm": "ជំពូកទី ៤ ភូមិវិទ្យាអាស៊ីអាគ្នេយ៍ និងពិភពលោក",
    "lessonTitleKm": "មេរៀនទី ១ បណ្តាប្រទេសក្នុងតំបន់អាស៊ីអាគ្នេយ៍ (ក. ទីតាំង និងសមាជិកអាស៊ាន)",
    "lessonTitleEn": "Chapter 4 Lesson 1: Southeast Asian Countries - ASEAN Members",
    "objectivesKm": "កំណត់ទីតាំងភូមិសាស្ត្រនៃបណ្តាប្រទេសទាំង ១១ ក្នុងតំបន់អាស៊ីអាគ្នេយ៍ និងសមាគមអាស៊ាន",
    "hoursCount": 4,
    "semester": 2,
    "status": "upcoming",
    "pageSs": "82-85"
  },
  {
    "id": "soc_g6_w24_01",
    "weekNumber": 24,
    "monthKm": "មេសា",
    "subjectId": "sub_social",
    "chapterKm": "ជំពូកទី ៤ ភូមិវិទ្យាអាស៊ីអាគ្នេយ៍ និងពិភពលោក",
    "lessonTitleKm": "មេរៀនទី ១ បណ្តាប្រទេសក្នុងតំបន់អាស៊ីអាគ្នេយ៍ (ខ. សេដ្ឋកិច្ច និងវប្បធម៌អាស៊ាន)",
    "lessonTitleEn": "Lesson 1: Economy & Diverse Cultures of ASEAN Nations",
    "objectivesKm": "ប្រៀបធៀបសេដ្ឋកិច្ច ធនធាន និងភាពចម្រុះនៃវប្បធម៌ក្នុងតំបន់អាស៊ីអាគ្នេយ៍",
    "hoursCount": 4,
    "semester": 2,
    "status": "upcoming",
    "pageSs": "86-89"
  },

  # ឧសភា (May)
  {
    "id": "soc_g6_w25_01",
    "weekNumber": 25,
    "monthKm": "ឧសភា",
    "subjectId": "sub_social",
    "chapterKm": "ជំពូកទី ៤ ភូមិវិទ្យាអាស៊ីអាគ្នេយ៍ និងពិភពលោក",
    "lessonTitleKm": "មេរៀនទី ២ ទ្វីបនានាលើពិភពលោក (ក. ទ្វីបអាស៊ី)",
    "lessonTitleEn": "Lesson 2: Continents of the World - Asia (Geography & Population)",
    "objectivesKm": "រៀបរាប់ពីទំហំ ភូមិសាស្ត្រ ប្រជាជន និងសេដ្ឋកិច្ចនៃទ្វីបអាស៊ី",
    "hoursCount": 4,
    "semester": 2,
    "status": "upcoming",
    "pageSs": "92-95"
  },
  {
    "id": "soc_g6_w26_01",
    "weekNumber": 26,
    "monthKm": "ឧសភា",
    "subjectId": "sub_social",
    "chapterKm": "ជំពូកទី ៤ ភូមិវិទ្យាអាស៊ីអាគ្នេយ៍ និងពិភពលោក",
    "lessonTitleKm": "មេរៀនទី ២ ទ្វីបនានាលើពិភពលោក (ខ. ទ្វីបអឺរ៉ុប និងទ្វីបអាហ្វ្រិក)",
    "lessonTitleEn": "Lesson 2: Europe & Africa - Characteristics & Climate",
    "objectivesKm": "បង្ហាញពីលក្ខណៈភូមិសាស្ត្រ អាកាសធាតុ និងប្រជាសាស្ត្រនៃទ្វីបអឺរ៉ុបនិងអាហ្វ្រិក",
    "hoursCount": 4,
    "semester": 2,
    "status": "upcoming",
    "pageSs": "96-99"
  },
  {
    "id": "soc_g6_w27_01",
    "weekNumber": 27,
    "monthKm": "ឧសភា",
    "subjectId": "sub_social",
    "chapterKm": "ជំពូកទី ៤ ភូមិវិទ្យាអាស៊ីអាគ្នេយ៍ និងពិភពលោក",
    "lessonTitleKm": "មេរៀនទី ២ ទ្វីបនានាលើពិភពលោក (គ. ទ្វីបអាមេរិក និងអូសេអានី)",
    "lessonTitleEn": "Lesson 2: The Americas & Oceania",
    "objectivesKm": "ពណ៌នាពីទ្វីបអាមេរិកខាងជើង អាមេរិកខាងត្បូង និងទ្វីបអូសេអានី",
    "hoursCount": 4,
    "semester": 2,
    "status": "upcoming",
    "pageSs": "100-103"
  },
  {
    "id": "soc_g6_w28_01",
    "weekNumber": 28,
    "monthKm": "ឧសភា",
    "subjectId": "sub_social",
    "chapterKm": "ជំពូកទី ៤ ភូមិវិទ្យាអាស៊ីអាគ្នេយ៍ និងពិភពលោក",
    "lessonTitleKm": "មេរៀនទី ៣ មហាសមុទ្រ និងបរិស្ថានផែនដី (ក. មហាសមុទ្រទាំង៥)",
    "lessonTitleEn": "Lesson 3: The 5 Oceans & Global Environment",
    "objectivesKm": "កំណត់ទីតាំងមហាសមុទ្រប៉ាស៊ីហ្វិក អាត្លង់ទិក ឥណ្ឌា អាកទិក និងអង់តាក់ទិក",
    "hoursCount": 4,
    "semester": 2,
    "status": "upcoming",
    "pageSs": "104-107"
  },

  # មិថុនា (Jun)
  {
    "id": "soc_g6_w29_01",
    "weekNumber": 29,
    "monthKm": "មិថុនា",
    "subjectId": "sub_social",
    "chapterKm": "ជំពូកទី ៤ ភូមិវិទ្យាអាស៊ីអាគ្នេយ៍ និងពិភពលោក",
    "lessonTitleKm": "មេរៀនទី ៣ មហាសមុទ្រ និងបរិស្ថានផែនដី (ខ. បម្រែបម្រួលអាកាសធាតុសកល)",
    "lessonTitleEn": "Lesson 3: Global Climate Change & Greenhouse Effect",
    "objectivesKm": "ពន្យល់ពីមូលហេតុនៃបាតុភូតឡើងកម្តៅផែនដី និងផលប៉ះពាល់លើបរិស្ថាន",
    "hoursCount": 4,
    "semester": 2,
    "status": "upcoming",
    "pageSs": "108-111"
  },
  {
    "id": "soc_g6_w30_01",
    "weekNumber": 30,
    "monthKm": "មិថុនា",
    "subjectId": "sub_social",
    "chapterKm": "ជំពូកទី ៥ បេតិកភណ្ឌវប្បធម៌ និងធម្មជាតិ",
    "lessonTitleKm": "មេរៀនទី ១ សម្បត្តិបេតិកភណ្ឌពិភពលោកនៅកម្ពុជា (ក. រមណីយដ្ឋានអង្គរ)",
    "lessonTitleEn": "Chapter 5 Lesson 1: UNESCO World Heritage in Cambodia - Angkor",
    "objectivesKm": "បង្ហាញពីតម្លៃជាសកលនៃរមណីយដ្ឋានអង្គរដែលបានចុះបញ្ជីបេតិកភណ្ឌពិភពលោក",
    "hoursCount": 4,
    "semester": 2,
    "status": "upcoming",
    "pageSs": "114-117"
  },
  {
    "id": "soc_g6_w31_01",
    "weekNumber": 31,
    "monthKm": "មិថុនា",
    "subjectId": "sub_social",
    "chapterKm": "ជំពូកទី ៥ បេតិកភណ្ឌវប្បធម៌ និងធម្មជាតិ",
    "lessonTitleKm": "មេរៀនទី ១ សម្បត្តិបេតិកភណ្ឌពិភពលោកនៅកម្ពុជា (ខ. ប្រាសាទព្រះវិហារ និងសំបូរព្រៃគុក)",
    "lessonTitleEn": "Lesson 1: Preah Vihear & Sambor Prei Kuk Temples",
    "objectivesKm": "ពណ៌នាអំពីប្រាសាទព្រះវិហារ និងតំបន់ប្រាសាទសំបូរព្រៃគុក",
    "hoursCount": 4,
    "semester": 2,
    "status": "upcoming",
    "pageSs": "118-121"
  },
  {
    "id": "soc_g6_w32_01",
    "weekNumber": 32,
    "monthKm": "មិថុនា",
    "subjectId": "sub_social",
    "chapterKm": "ជំពូកទី ៥ បេតិកភណ្ឌវប្បធម៌ និងធម្មជាតិ",
    "lessonTitleKm": "មេរៀនទី ២ បេតិកភណ្ឌអរូបីនៃមនុស្សជាតិ (ក. ល្ខោនស្រមោលស្បែកធំ និងល្ខោនខោល)",
    "lessonTitleEn": "Lesson 2: Intangible Cultural Heritage - Sbek Thom & Lakhon Khol",
    "objectivesKm": "ស្គាល់ពីទម្រង់ល្ខោនស្បែកធំ ល្ខោនខោល និងចាប៉ីដងវែង",
    "hoursCount": 4,
    "semester": 2,
    "status": "upcoming",
    "pageSs": "122-125"
  },

  # កក្កដា (Jul)
  {
    "id": "soc_g6_w33_01",
    "weekNumber": 33,
    "monthKm": "កក្កដា",
    "subjectId": "sub_social",
    "chapterKm": "ជំពូកទី ៥ បេតិកភណ្ឌវប្បធម៌ និងធម្មជាតិ",
    "lessonTitleKm": "មេរៀនទី ៣ ការអភិរក្ស និងលើកកម្ពស់វប្បធម៌ជាតិ (ក. ការថែរក្សាបេតិកភណ្ឌ)",
    "lessonTitleEn": "Lesson 3: Preservation & Promotion of National Cultural Heritage",
    "objectivesKm": "ចូលរួមការពារ និងថែរក្សាវត្ថុបុរាណ ប្រាសាទ និងប្រពៃណីទំនៀមទម្លាប់ខ្មែរ",
    "hoursCount": 4,
    "semester": 2,
    "status": "upcoming",
    "pageSs": "126-129"
  },
  {
    "id": "soc_g6_w34_01",
    "weekNumber": 34,
    "monthKm": "កក្កដា",
    "subjectId": "sub_social",
    "chapterKm": "ជំពូកទី ៥ បេតិកភណ្ឌវប្បធម៌ និងធម្មជាតិ",
    "lessonTitleKm": "មេរៀនទី ៤ ទីក្រុងស្អាត និងទេសចរណ៍បៃតង (ក. ចលនាប្រឡងប្រណាំងទីក្រុងស្អាត)",
    "lessonTitleEn": "Lesson 4: Clean City Contest & Green Eco-Tourism",
    "objectivesKm": "យល់ដឹងពីសូចនាករទីក្រុងស្អាត ការគ្រប់គ្រងសំរាម និងទេសចរណ៍ធម្មជាតិ",
    "hoursCount": 4,
    "semester": 2,
    "status": "upcoming",
    "pageSs": "130-133"
  },
  {
    "id": "soc_g6_w35_01",
    "weekNumber": 35,
    "monthKm": "កក្កដា",
    "subjectId": "sub_social",
    "chapterKm": "ជំពូកទី ៥ បេតិកភណ្ឌវប្បធម៌ និងធម្មជាតិ",
    "lessonTitleKm": "មេរៀនទី ៤ ទីក្រុងស្អាត និងទេសចរណ៍បៃតង (ខ. សកម្មភាពចូលរួមរបស់យុវជន)",
    "lessonTitleEn": "Lesson 4: Youth Participation in Environmental Protection",
    "objectivesKm": "លើកទឹកចិត្តឱ្យសិស្សានុសិស្សចូលរួមសកម្មភាពដាំដើមឈើ និងសម្អាតបរិស្ថាន",
    "hoursCount": 4,
    "semester": 2,
    "status": "upcoming",
    "pageSs": "134-137"
  },

  # សីហា (Aug)
  {
    "id": "soc_g6_w36_01",
    "weekNumber": 36,
    "monthKm": "សីហា",
    "subjectId": "sub_social",
    "chapterKm": "រៀនសារឡើងវិញ និងប្រឡងឆមាសទី២",
    "lessonTitleKm": "រៀនសារឡើងវិញមេរៀនសិក្សាសង្គម ថ្នាក់ទី៦ ទាំងមូល",
    "lessonTitleEn": "Comprehensive Revision of Grade 6 Social Studies",
    "objectivesKm": "រំលឹកឡើងវិញនូវចំណេះដឹងសីលធម៌ ប្រវត្តិវិទ្យា ភូមិវិទ្យា និងបេតិកភណ្ឌវប្បធម៌",
    "hoursCount": 4,
    "semester": 2,
    "status": "upcoming",
    "notes": "រៀនសារឡើងវិញ"
  },
  {
    "id": "soc_g6_w36_02",
    "weekNumber": 36,
    "monthKm": "សីហា",
    "subjectId": "sub_social",
    "chapterKm": "រៀនសារឡើងវិញ និងប្រឡងឆមាសទី២",
    "lessonTitleKm": "ការប្រឡងបញ្ចប់ឆ្នាំសិក្សា និងប្រឡងបញ្ចប់កម្រិតបឋមសិក្សា",
    "lessonTitleEn": "Final Year Examination & Primary School Completion Evaluation",
    "objectivesKm": "វាយតម្លៃបញ្ចប់កម្រិតបឋមសិក្សាថ្នាក់ទី៦",
    "hoursCount": 4,
    "semester": 2,
    "status": "upcoming",
    "isExamOrHoliday": True,
    "notes": "ប្រឡងបញ្ចប់កម្រិតបឋមសិក្សា / ឆមាសទី២"
  }
]

make_social_file(
  'src/data/curriculumSocialGrade6.ts',
  'CURRICULUM_SOCIAL_GRADE6',
  'prog_social_g6',
  6,
  'កម្មវិធីសិក្សាសង្គម ថ្នាក់ទី៦ (MoEYS)',
  'Social Studies Grade 6 Curriculum',
  g6_lessons
)

print("Grade 6 Social Studies built successfully!")
