import json
from generate_social_data import make_social_file

g3_lessons = [
  # វិច្ឆិកា (Nov)
  {
    "id": "soc_g3_w01_01",
    "weekNumber": 1,
    "monthKm": "វិច្ឆិកា",
    "subjectId": "sub_social",
    "chapterKm": "ជំពូកទី ១ ការរស់នៅប្រកបដោយអនាម័យ",
    "lessonTitleKm": "មេរៀនទី ១ ការសម្អាតខ្លួនប្រាណ (មុខងារ ភ្នែក ច្រមុះ មាត់ ត្រចៀក និងស្បែក)",
    "lessonTitleEn": "Chapter 1 Lesson 1: Personal Hygiene - Sensory Organs",
    "objectivesKm": "ពន្យល់និងដោយឧទាហរណ៍ពីមុខងាររបស់ភ្នែក ច្រមុះ មាត់ ត្រចៀក និងស្បែក",
    "hoursCount": 2,
    "semester": 1,
    "status": "completed",
    "pageSs": "2"
  },
  {
    "id": "soc_g3_w02_01",
    "weekNumber": 2,
    "monthKm": "វិច្ឆិកា",
    "subjectId": "sub_social",
    "chapterKm": "ជំពូកទី ១ ការរស់នៅប្រកបដោយអនាម័យ",
    "lessonTitleKm": "រំលឹកឡើងវិញ មេរៀនវិទ្យាសាស្ត្រ និងសិក្សាសង្គម ថ្នាក់ទី២",
    "lessonTitleEn": "Revision of Grade 2 Social Studies & Science",
    "objectivesKm": "រំលឹកឡើងវិញនូវមូលដ្ឋានគ្រឹះអនាម័យពីថ្នាក់ទី២",
    "hoursCount": 1,
    "semester": 1,
    "status": "completed",
    "pageSs": "1",
    "notes": "រំលឹកឡើងវិញ"
  },
  {
    "id": "soc_g3_w02_02",
    "weekNumber": 2,
    "monthKm": "វិច្ឆិកា",
    "subjectId": "sub_social",
    "chapterKm": "ជំពូកទី ១ ការរស់នៅប្រកបដោយអនាម័យ",
    "lessonTitleKm": "មេរៀនទី ១ ការសម្អាតខ្លួនប្រាណ (ការថែរក្សា ភ្នែក ច្រមុះ ធ្មេញ ខ្លួនប្រាណ)",
    "lessonTitleEn": "Lesson 1: Personal Hygiene - Body Care & Teeth Cleaning",
    "objectivesKm": "រៀបរាប់ពីរបៀបថែរក្សា និងសម្អាតភ្នែក ច្រមុះ ធ្មេញ និងខ្លួនប្រាណ",
    "hoursCount": 2,
    "semester": 1,
    "status": "completed",
    "pageSs": "3"
  },
  {
    "id": "soc_g3_w03_01",
    "weekNumber": 3,
    "monthKm": "វិច្ឆិកា",
    "subjectId": "sub_social",
    "chapterKm": "ជំពូកទី ១ ការរស់នៅប្រកបដោយអនាម័យ",
    "lessonTitleKm": "មេរៀនទី ២ ការបង្ការខ្លួនពីជំងឺផ្សេងៗ",
    "lessonTitleEn": "Lesson 2: Preventing Diseases",
    "objectivesKm": "យល់ដឹងពីវិធីបង្ការ និងថែរក្សាសុខភាពពីជំងឺផ្សេងៗ",
    "hoursCount": 2,
    "semester": 1,
    "status": "completed",
    "pageSs": "4"
  },
  {
    "id": "soc_g3_w04_01",
    "weekNumber": 4,
    "monthKm": "វិច្ឆិកា",
    "subjectId": "sub_social",
    "chapterKm": "ជំពូកទី ១ ការរស់នៅប្រកបដោយអនាម័យ",
    "lessonTitleKm": "មេរៀនទី ២ ការបង្ការខ្លួនពីជំងឺផ្សេងៗ (កុមារច្រើនកើតជំងឺ)",
    "lessonTitleEn": "Lesson 2: Common Childhood Illnesses",
    "objectivesKm": "បង្ហាញមូលហេតុនៃការកើតជំងឺដូចជា ជំងឺកញ្ជ្រឹល ផ្តាសាយ ក្អួតចង្អោរ និង រាករួស",
    "hoursCount": 2,
    "semester": 1,
    "status": "completed",
    "pageSs": "6"
  },

  # ធ្នូ (Dec)
  {
    "id": "soc_g3_w05_01",
    "weekNumber": 5,
    "monthKm": "ធ្នូ",
    "subjectId": "sub_social",
    "chapterKm": "ជំពូកទី ១ ការរស់នៅប្រកបដោយអនាម័យ",
    "lessonTitleKm": "មេរៀនទី ២ ការបង្ការខ្លួនពីជំងឺផ្សេងៗ (ជំងឺផ្តាសាយ ក្អួតចង្អោរ រាករួស កញ្ជ្រឹល)",
    "lessonTitleEn": "Lesson 2: Flu, Diarrhea, Vomiting & Measles Causes",
    "objectivesKm": "ប្រាប់ពីមូលហេតុនៃការកើតជំងឺផ្តាសាយ ក្អួតចង្អោរ រាករូស និងកញ្ជ្រឹល",
    "hoursCount": 3,
    "semester": 1,
    "status": "completed",
    "pageSs": "7"
  },
  {
    "id": "soc_g3_w06_01",
    "weekNumber": 6,
    "monthKm": "ធ្នូ",
    "subjectId": "sub_social",
    "chapterKm": "ជំពូកទី ១ ការរស់នៅប្រកបដោយអនាម័យ",
    "lessonTitleKm": "មេរៀនទី ៣ ចំណីអាហារស្អាត (ការបរិភោគចំណីអាហារដែលមានអនាម័យល្អ)",
    "lessonTitleEn": "Lesson 3: Clean Food - Eating Clean & Safe Food Storage",
    "objectivesKm": "ពន្យល់ពីរៀបទុកដាក់ចំណីអាហារប្រកបដោយសុវត្ថិភាព",
    "hoursCount": 2,
    "semester": 1,
    "status": "completed",
    "pageSs": "10"
  },
  {
    "id": "soc_g3_w07_01",
    "weekNumber": 7,
    "monthKm": "ធ្នូ",
    "subjectId": "sub_social",
    "chapterKm": "ជំពូកទី ១ ការរស់នៅប្រកបដោយអនាម័យ",
    "lessonTitleKm": "មេរៀនទី ៣ ចំណីអាហារស្អាត (ដើម្បីឱ្យចំណីអាហារមានអនាម័យល្អយើងត្រូវ៖)",
    "lessonTitleEn": "Lesson 3: Clean Food - Food Safety Rules",
    "objectivesKm": "ពន្យល់ពីសារៈសំខាន់នៃការបរិភោគចំណីអាហារដែលមានអនាម័យល្អ",
    "hoursCount": 2,
    "semester": 1,
    "status": "completed",
    "pageSs": "10"
  },
  {
    "id": "soc_g3_w08_01",
    "weekNumber": 8,
    "monthKm": "ធ្នូ",
    "subjectId": "sub_social",
    "chapterKm": "ជំពូកទី ១ ការរស់នៅប្រកបដោយអនាម័យ",
    "lessonTitleKm": "មេរៀនទី ៣ ចំណីអាហារស្អាត (សារៈសំខាន់ទឹកស្អាត និងលំហាត់កិច្ចការផ្ទះ)",
    "lessonTitleEn": "Lesson 3: Importance of Clean Water & Homework Exercises",
    "objectivesKm": "ពន្យល់ពីសារៈសំខាន់នៃទឹកស្អាត និងបង្ហាញពីរៀបផលិតទឹកស្អាត",
    "hoursCount": 2,
    "semester": 1,
    "status": "completed",
    "pageSs": "12-13",
    "notes": "លំហាត់"
  },

  # មករា (Jan)
  {
    "id": "soc_g3_w09_01",
    "weekNumber": 9,
    "monthKm": "មករា",
    "subjectId": "sub_social",
    "chapterKm": "ជំពូកទី ១ ការរស់នៅប្រកបដោយអនាម័យ",
    "lessonTitleKm": "មេរៀនទី ៤ ការទទួលស្គាល់អំពើល្អ (អំពើល្អរបស់មិត្តខ្ញុំ & អ្នកដែលខ្ញុំស្ញើចសរសើរ)",
    "lessonTitleEn": "Lesson 4: Recognizing Good Deeds - Admiring Friends & Role Models",
    "objectivesKm": "ចូលរួមក្នុងសកម្មភាពផ្សេងៗដើម្បីស្វែងយល់ពីអំពើល្អចំពោះមិត្តភក្តិ និងស្តាប់អ្នកដទៃនិយាយរៀបរាប់អំពើល្អ",
    "hoursCount": 2,
    "semester": 1,
    "status": "completed",
    "pageSs": "14-16"
  },
  {
    "id": "soc_g3_w10_01",
    "weekNumber": 10,
    "monthKm": "មករា",
    "subjectId": "sub_social",
    "chapterKm": "ជំពូកទី ១ ការរស់នៅប្រកបដោយអនាម័យ",
    "lessonTitleKm": "មេរៀនទី ៥ សណ្តាប់ធ្នាប់ល្អ (កិច្ចការរបស់សិស្ស)",
    "lessonTitleEn": "Lesson 5: Good Order - Student Duties & Planning",
    "objectivesKm": "ជ្រើសរើសកិច្ចការណាមួយ និងសរសេរលំដាប់លំដោយនៃសកម្មភាពសំខាន់ៗដែលត្រូវអនុវត្ត",
    "hoursCount": 2,
    "semester": 1,
    "status": "completed",
    "pageSs": "18"
  },
  {
    "id": "soc_g3_w11_01",
    "weekNumber": 11,
    "monthKm": "មករា",
    "subjectId": "sub_social",
    "chapterKm": "ជំពូកទី ១ ការរស់នៅប្រកបដោយអនាម័យ",
    "lessonTitleKm": "មេរៀនទី ៥ សណ្តាប់ធ្នាប់ល្អ (របៀបធ្វើកិច្ចការដើម្បីបានជោគជ័យ និងលំហាត់)",
    "lessonTitleEn": "Lesson 5: Achieving Success in Tasks & Exercises",
    "objectivesKm": "ពន្យល់និងដោយឧទាហរណ៍ពីរបៀបធ្វើកិច្ចការដើម្បីបានជោគជ័យ",
    "hoursCount": 2,
    "semester": 1,
    "status": "completed",
    "pageSs": "19-20",
    "notes": "លំហាត់"
  },
  {
    "id": "soc_g3_w12_01",
    "weekNumber": 12,
    "monthKm": "មករា",
    "subjectId": "sub_social",
    "chapterKm": "ជំពូកទី ២ ទម្លាប់រស់នៅក្នុងសហគមន៍",
    "lessonTitleKm": "មេរៀនទី ១ ការស្រឡាញ់រាប់អានគ្នា (សីលធម៌ គោរពច្បាប់ វិន័យ)",
    "lessonTitleEn": "Chapter 2 Lesson 1: Loving and Respecting One Another - Ethics & Rules",
    "objectivesKm": "កំណត់សារៈសំខាន់នៃសីលធម៌ល្អ និងបង្ហាញពីមូលហេតុនៃការគោរពច្បាប់និងវិន័យក្នុងសហគមន៍",
    "hoursCount": 3,
    "semester": 1,
    "status": "completed",
    "pageSs": "22-24"
  },

  # កុម្ភៈ (Feb)
  {
    "id": "soc_g3_w13_01",
    "weekNumber": 13,
    "monthKm": "កុម្ភៈ",
    "subjectId": "sub_social",
    "chapterKm": "ជំពូកទី ២ ទម្លាប់រស់នៅក្នុងសហគមន៍",
    "lessonTitleKm": "មេរៀនទី ២ ការយកចិត្តទុកដាក់ចំពោះអ្នកនៅជុំវិញ (ទ្រព្យសម្បត្តិអ្នកដទៃ & ទ្រព្យសាធារណៈ)",
    "lessonTitleEn": "Lesson 2: Caring for People & Public Property",
    "objectivesKm": "ពន្យល់ពីមូលហេតុនៃការថែរក្សានិងមិនយកវត្ថុអ្នកដទៃ និងការថែរក្សាទ្រព្យសម្បត្តិសាធារណៈ",
    "hoursCount": 3,
    "semester": 1,
    "status": "in_progress",
    "pageSs": "26-28"
  },
  {
    "id": "soc_g3_w14_01",
    "weekNumber": 14,
    "monthKm": "កុម្ភៈ",
    "subjectId": "sub_social",
    "chapterKm": "ជំពូកទី ២ ទម្លាប់រស់នៅក្នុងសហគមន៍",
    "lessonTitleKm": "មេរៀនទី ៣ ការរក្សាសុវត្ថិភាពពេលធ្វើដំណើរផ្លូវ (មួកសុវត្ថិភាព & គំនូសចរាចរណ៍)",
    "lessonTitleEn": "Lesson 3: Road Safety - Helmets & Road Markings",
    "objectivesKm": "ពន្យល់ពីមូលហេតុនៃការពាក់មួកសុវត្ថិភាពពេលជិះកង់ ម៉ូតូ និងគំនូសចរាចរណ៍លើទ្រូងផ្លូវ",
    "hoursCount": 3,
    "semester": 1,
    "status": "in_progress",
    "pageSs": "30-32"
  },
  {
    "id": "soc_g3_w15_01",
    "weekNumber": 15,
    "monthKm": "កុម្ភៈ",
    "subjectId": "sub_social",
    "chapterKm": "ជំពូកទី ២ ទម្លាប់រស់នៅក្នុងសហគមន៍",
    "lessonTitleKm": "មេរៀនទី ៣ ការរក្សាសុវត្ថិភាពពេលធ្វើដំណើរផ្លូវ (លំហាត់កិច្ចការផ្ទះ)",
    "lessonTitleEn": "Lesson 3: Road Safety - Exercises",
    "objectivesKm": "ធ្វើកិច្ចការផ្ទះ និងអនុវត្តច្បាប់ចរាចរណ៍បានត្រឹមត្រូវ",
    "hoursCount": 2,
    "semester": 1,
    "status": "in_progress",
    "pageSs": "33",
    "notes": "លំហាត់"
  },
  {
    "id": "soc_g3_w16_01",
    "weekNumber": 16,
    "monthKm": "កុម្ភៈ",
    "subjectId": "sub_social",
    "chapterKm": "ជំពូកទី ២ ទម្លាប់រស់នៅក្នុងសហគមន៍",
    "lessonTitleKm": "មេរៀនទី ៤ ការរក្សាសុវត្ថិភាពនៅក្នុងតំបន់មានមីន (គ្រោះថ្នាក់មីន & សញ្ញាសម្គាល់មីន)",
    "lessonTitleEn": "Lesson 4: Mine Risk Education - Mine Dangers & Warning Signs",
    "objectivesKm": "ពន្យល់ពីគ្រោះថ្នាក់ដែលបង្កឡើងដោយសារមីន និងបណ្តុះស្មារតីសិស្សឱ្យប្រុងប្រយ័ត្នចំពោះផ្លាកសញ្ញាមីន",
    "hoursCount": 3,
    "semester": 1,
    "status": "in_progress",
    "pageSs": "34-35"
  },

  # មីនា (Mar)
  {
    "id": "soc_g3_w17_01",
    "weekNumber": 17,
    "monthKm": "មីនា",
    "subjectId": "sub_social",
    "chapterKm": "ជំពូកទី ២ ទម្លាប់រស់នៅក្នុងសហគមន៍",
    "lessonTitleKm": "មេរៀនទី ៤ ការរក្សាសុវត្ថិភាពនៅក្នុងតំបន់មានមីន (ឥរិយាបថល្អក្នុងតំបន់មានមីន)",
    "lessonTitleEn": "Lesson 4: Safe Behavior in Mine Areas & Exercises",
    "objectivesKm": "រៀបរាប់ពីឥរិយាបថល្អក្នុងតំបន់មានមីន និងការថែរក្សាសញ្ញាសម្គាល់មីន",
    "hoursCount": 2,
    "semester": 1,
    "status": "upcoming",
    "pageSs": "36"
  },
  {
    "id": "soc_g3_w17_02",
    "weekNumber": 17,
    "monthKm": "មីនា",
    "subjectId": "sub_social",
    "chapterKm": "ជំពូកទី ២ ទម្លាប់រស់នៅក្នុងសហគមន៍",
    "lessonTitleKm": "មេរៀនទី ៥ ការចៀសវាងពីការគំរាមកំហែង (ចំណង់ចំណូលចិត្ត & ស្ថានភាពគ្មានសុវត្ថិភាព)",
    "lessonTitleEn": "Lesson 5: Avoiding Threats & Predators",
    "objectivesKm": "បង្ហាញពីសកម្មភាពដែលអាចឈានទៅរកស្ថានភាពគ្មានសុវត្ថិភាពពេលមានគេគំរាមកំហែង",
    "hoursCount": 1,
    "semester": 1,
    "status": "upcoming",
    "pageSs": "37-38"
  },
  {
    "id": "soc_g3_w18_01",
    "weekNumber": 18,
    "monthKm": "មីនា",
    "subjectId": "sub_social",
    "chapterKm": "ជំពូកទី ២ ទម្លាប់រស់នៅក្នុងសហគមន៍",
    "lessonTitleKm": "មេរៀនទី ៥ ការចៀសវាងពីការគំរាមកំហែង (ល្បិចជនខិលខូច & វិធីការពារខ្លួន)",
    "lessonTitleEn": "Lesson 5: Tricks of Bad People & Self Defense",
    "objectivesKm": "ប្រាប់ពីករណីរងគ្រោះរបស់កុមារ ល្បិចផ្សេងៗរបស់ជនខិលខូច និងវិធីការពារខ្លួន",
    "hoursCount": 2,
    "semester": 1,
    "status": "upcoming",
    "pageSs": "39-40"
  },
  {
    "id": "soc_g3_w18_02",
    "weekNumber": 18,
    "monthKm": "មីនា",
    "subjectId": "sub_social",
    "chapterKm": "ជំពូកទី ២ ទម្លាប់រស់នៅក្នុងសហគមន៍",
    "lessonTitleKm": "ការវាយតម្លៃ និងប្រឡងឆមាសទី១",
    "lessonTitleEn": "Semester 1 Evaluation & Assessment",
    "objectivesKm": "វាយតម្លៃសមត្ថភាព និងចំណេះដឹងសិស្សប្រចាំឆមាសទី១",
    "hoursCount": 3,
    "semester": 1,
    "status": "upcoming",
    "isExamOrHoliday": True,
    "notes": "ប្រឡងឆមាសទី១"
  },

  # Semester 2
  {
    "id": "soc_g3_w19_01",
    "weekNumber": 19,
    "monthKm": "មីនា",
    "subjectId": "sub_social",
    "chapterKm": "ជំពូកទី ២ ទម្លាប់រស់នៅក្នុងសហគមន៍",
    "lessonTitleKm": "មេរៀនទី ៦ ការទុកដាក់វត្ថុឱ្យមានសុវត្ថិភាព (សម្ភារប្រើប្រាស់ & ការបង្ការគ្រោះថ្នាក់)",
    "lessonTitleEn": "Lesson 6: Safe Storage of Household Items",
    "objectivesKm": "ឱ្យឧទាហរណ៍ពីវត្ថុក្នុងផ្ទះដែលអាចបង្កគ្រោះថ្នាក់ និងស្គាល់របៀបទុកដាក់វត្ថុឱ្យមានសុវត្ថិភាព",
    "hoursCount": 3,
    "semester": 2,
    "status": "upcoming",
    "pageSs": "42-44"
  },
  {
    "id": "soc_g3_w20_01",
    "weekNumber": 20,
    "monthKm": "មីនា",
    "subjectId": "sub_social",
    "chapterKm": "ជំពូកទី ៣ ការលូតលាស់នៃមនុស្ស សត្វ និងរុក្ខជាតិ",
    "lessonTitleKm": "មេរៀនទី ១ បន្ទាត់ពេលវេលា (ដំណើរជីវិត & ការប្រើប្រាស់បន្ទាត់ពេលវេលា)",
    "lessonTitleEn": "Chapter 3 Lesson 1: Timelines - Grandma's Life Journey",
    "objectivesKm": "រៀបរាប់ពីព្រឹត្តិការណ៍ជីវិត និងចេះគូសបន្ទាត់ពេលវេលាបង្ហាញពីព្រឹត្តិការណ៍សំខាន់ៗ",
    "hoursCount": 4,
    "semester": 2,
    "status": "upcoming",
    "pageSs": "46-49"
  },

  # មេសា (Apr)
  {
    "id": "soc_g3_w21_01",
    "weekNumber": 21,
    "monthKm": "មេសា",
    "subjectId": "sub_social",
    "chapterKm": "ជំពូកទី ៣ ការលូតលាស់នៃមនុស្ស សត្វ និងរុក្ខជាតិ",
    "lessonTitleKm": "មេរៀនទី ២ រុក្ខជាតិដែលខ្ញុំដាំ (ការដុះលូតលាស់ សារៈប្រយោជន៍ និងការថែទាំ)",
    "lessonTitleEn": "Lesson 2: Plants I Grow - Stages, Benefits & Tree Preservation",
    "objectivesKm": "បង្ហាញពីដំណាក់កាលលូតលាស់ សារប្រយោជន៍ និងផលអាក្រក់នៃការបាត់បង់ព្រៃឈើ",
    "hoursCount": 3,
    "semester": 2,
    "status": "upcoming",
    "pageSs": "50-52"
  },
  {
    "id": "soc_g3_w24_01",
    "weekNumber": 24,
    "monthKm": "មេសា",
    "subjectId": "sub_social",
    "chapterKm": "ជំពូកទី ៣ ការលូតលាស់នៃមនុស្ស សត្វ និងរុក្ខជាតិ",
    "lessonTitleKm": "មេរៀនទី ៣ សត្វដែលខ្ញុំចិញ្ចឹម (ចំណាត់ថ្នាក់សត្វ ផលប្រយោជន៍ និងរបៀបចិញ្ចឹម)",
    "lessonTitleEn": "Lesson 3: Animals I Care For - Animal Classification & Farming",
    "objectivesKm": "ធ្វើចំណាត់ថ្នាក់សត្វ (ល្មូន សត្វល្អិត សត្វគោក សត្វទឹក) និងប្រាប់ពីផលប្រយោជន៍និងការចិញ្ចឹម",
    "hoursCount": 4,
    "semester": 2,
    "status": "upcoming",
    "pageSs": "54-57"
  },

  # ឧសភា (May)
  {
    "id": "soc_g3_w25_01",
    "weekNumber": 25,
    "monthKm": "ឧសភា",
    "subjectId": "sub_social",
    "chapterKm": "ជំពូកទី ៣ ជីវភាពប្រជាជននៅសហគមន៍ខ្ញុំ",
    "lessonTitleKm": "មេរៀនទី ១ ទីកន្លែងដែលខ្ញុំរស់នៅ (ទីតាំងស្រុកឬខណ្ឌដែលខ្ញុំរស់នៅ)",
    "lessonTitleEn": "Chapter 3 Lesson 1: Where I Live - My District on Cambodia Map",
    "objectivesKm": "បង្ហាញទីតាំងក្នុងស្រុក ដែលខ្លួនរស់នៅលើផែនទីនៃប្រទេសកម្ពុជា",
    "hoursCount": 2,
    "semester": 2,
    "status": "upcoming",
    "pageSs": "60"
  },
  {
    "id": "soc_g3_w26_01",
    "weekNumber": 26,
    "monthKm": "ឧសភា",
    "subjectId": "sub_social",
    "chapterKm": "ជំពូកទី ៣ ជីវភាពប្រជាជននៅសហគមន៍ខ្ញុំ",
    "lessonTitleKm": "មេរៀនទី ១ ទីកន្លែងដែលខ្ញុំរស់នៅ (លំហាត់រាប់ឈ្មោះស្រុក ឃុំ ភូមិ និងគូរផែនទី)",
    "lessonTitleEn": "Lesson 1: Where I Live - Districts, Communes & Mapping",
    "objectivesKm": "រាប់ឈ្មោះរដ្ឋបាលក្នុងមូលដ្ឋាន និងអនុវត្តគូរផែនទីស្រុក",
    "hoursCount": 2,
    "semester": 2,
    "status": "upcoming",
    "pageSs": "60-61",
    "notes": "គូរផែនទី"
  },
  {
    "id": "soc_g3_w27_01",
    "weekNumber": 27,
    "monthKm": "ឧសភា",
    "subjectId": "sub_social",
    "chapterKm": "ជំពូកទី ៣ ជីវភាពប្រជាជននៅសហគមន៍ខ្ញុំ",
    "lessonTitleKm": "មេរៀនទី ១ ទីកន្លែងដែលខ្ញុំរស់នៅ (ទេសភាពស្រុកខ្ញុំ) និងមេរៀនទី ២ កន្លែងផ្សេងៗនៅភូមិខ្ញុំ",
    "lessonTitleEn": "Lesson 1-2: District Landscapes & Places in My Village",
    "objectivesKm": "បង្ហាញពីទេសភាពក្នុងស្រុក ភូមិ និងរៀបរាប់ពីកន្លែងផ្សេងៗនៅភូមិខ្ញុំ",
    "hoursCount": 3,
    "semester": 2,
    "status": "upcoming",
    "pageSs": "62-64"
  },
  {
    "id": "soc_g3_w28_01",
    "weekNumber": 28,
    "monthKm": "ឧសភា",
    "subjectId": "sub_social",
    "chapterKm": "ជំពូកទី ៣ ជីវភាពប្រជាជននៅសហគមន៍ខ្ញុំ",
    "lessonTitleKm": "មេរៀនទី ២ កន្លែងផ្សេងៗនៅភូមិខ្ញុំ (គូរទីតាំងកន្លែងសំខាន់ៗ & ផ្លូវពីផ្ទះទៅសាលា)",
    "lessonTitleEn": "Lesson 2: Mapping Important Village Locations & Route to School",
    "objectivesKm": "គូសនិងផាត់ពណ៌ផែនទីបង្ហាញផ្លូវទៅសាលារៀន និងកន្លែងសំខាន់ៗក្នុងភូមិ",
    "hoursCount": 3,
    "semester": 2,
    "status": "upcoming",
    "pageSs": "65-66"
  },

  # មិថុនា (Jun)
  {
    "id": "soc_g3_w29_01",
    "weekNumber": 29,
    "monthKm": "មិថុនា",
    "subjectId": "sub_social",
    "chapterKm": "ជំពូកទី ៣ ជីវភាពប្រជាជននៅសហគមន៍ខ្ញុំ",
    "lessonTitleKm": "មេរៀនទី ៣ រុក្ខជាតិនានានៅភូមិខ្ញុំ (រុក្ខជាតិនានា & ចំណាត់ថ្នាក់រុក្ខជាតិ)",
    "lessonTitleEn": "Lesson 3: Village Flora & Botanical Classification",
    "objectivesKm": "ប្រមូលសង្កេត ប្រៀបធៀប និងបែងចែករុក្ខជាតិតាមក្រុម (វល្លិ៍ ឈើ រុក្ខជាតិខ្ពស់ និងទាប)",
    "hoursCount": 3,
    "semester": 2,
    "status": "upcoming",
    "pageSs": "68-69"
  },
  {
    "id": "soc_g3_w30_01",
    "weekNumber": 30,
    "monthKm": "មិថុនា",
    "subjectId": "sub_social",
    "chapterKm": "ជំពូកទី ៣ ជីវភាពប្រជាជននៅសហគមន៍ខ្ញុំ",
    "lessonTitleKm": "មេរៀនទី ៣ រុក្ខជាតិនានានៅភូមិខ្ញុំ (ទីកន្លែងដែលរុក្ខជាតិដុះ លក្ខណៈរបស់រុក្ខជាតិ)",
    "lessonTitleEn": "Lesson 3: Plant Habitats & Environmental Adaptations",
    "objectivesKm": "ប្រៀបធៀបលក្ខណៈសម្គាល់រុក្ខជាតិដែលដុះក្នុងទឹក ឬលើដីមានសំណើម និងដីស្ងួត",
    "hoursCount": 2,
    "semester": 2,
    "status": "upcoming",
    "pageSs": "70-71"
  },
  {
    "id": "soc_g3_w31_01",
    "weekNumber": 31,
    "monthKm": "មិថុនា",
    "subjectId": "sub_social",
    "chapterKm": "ជំពូកទី ៣ ជីវភាពប្រជាជននៅសហគមន៍ខ្ញុំ",
    "lessonTitleKm": "មេរៀនទី ៤ ខ្ញុំរៀនច្រៀងចម្រៀង (បទនគររាជ ចម្រៀងជាតិ)",
    "lessonTitleEn": "Lesson 4: Singing Lessons - National Anthem (Nokoreach)",
    "objectivesKm": "រៀនច្រៀងចម្រៀងជាតិបានត្រឹមត្រូវនិងពិរោះ",
    "hoursCount": 2,
    "semester": 2,
    "status": "upcoming",
    "pageSs": "72"
  },
  {
    "id": "soc_g3_w32_01",
    "weekNumber": 32,
    "monthKm": "មិថុនា",
    "subjectId": "sub_social",
    "chapterKm": "ជំពូកទី ៣ ជីវភាពប្រជាជននៅសហគមន៍ខ្ញុំ",
    "lessonTitleKm": "មេរៀនទី ៤ ខ្ញុំរៀនច្រៀងចម្រៀង (បទអរអរសាទរ ពេលព្រឹកព្រលឹម ស្រីស្រុកស្រូវ ម្លប់ដូង)",
    "lessonTitleEn": "Lesson 4: Traditional Folk Songs",
    "objectivesKm": "រៀនច្រៀងបទប្រជាប្រិយ និងបទប្រពៃណីជាតិ",
    "hoursCount": 4,
    "semester": 2,
    "status": "upcoming",
    "pageSs": "73-75"
  },

  # កក្កដា (Jul)
  {
    "id": "soc_g3_w33_01",
    "weekNumber": 33,
    "monthKm": "កក្កដា",
    "subjectId": "sub_social",
    "chapterKm": "ជំពូកទី ៣ ជីវភាពប្រជាជននៅសហគមន៍ខ្ញុំ",
    "lessonTitleKm": "មេរៀនទី ៥ ខ្ញុំហាត់រាំ (ចង្វាក់រាំវង់បែបទី២ បែបទី៣ និងបែបទី៤)",
    "lessonTitleEn": "Lesson 5: Traditional Dance - Ramvong Steps 2, 3 & 4",
    "objectivesKm": "រៀនរាំវង់តាមចង្វាក់បែបទី២ បែបទី៣ និងបែបទី៤",
    "hoursCount": 4,
    "semester": 2,
    "status": "upcoming",
    "pageSs": "76-79"
  },
  {
    "id": "soc_g3_w34_01",
    "weekNumber": 34,
    "monthKm": "កក្កដា",
    "subjectId": "sub_social",
    "chapterKm": "ជំពូកទី ៣ ជីវភាពប្រជាជននៅសហគមន៍ខ្ញុំ",
    "lessonTitleKm": "មេរៀនទី ៦ ខ្ញុំរៀនត្បាញនិងបិទរូប (តម្បាញ គូសផាត់ពណ៌ និងកាត់បិទទង់ជាតិកម្ពុជា)",
    "lessonTitleEn": "Lesson 6: Weaving Crafts & National Flag Artwork",
    "objectivesKm": "អនុវត្តហាត់ត្បាញលើកមួយសង្កត់មួយ លើកពីរសង្កត់ពីរ និងកាត់បិទទង់ជាតិកម្ពុជា",
    "hoursCount": 4,
    "semester": 2,
    "status": "upcoming",
    "pageSs": "80-83"
  },
  {
    "id": "soc_g3_w35_01",
    "weekNumber": 35,
    "monthKm": "កក្កដា",
    "subjectId": "sub_social",
    "chapterKm": "ជំពូកទី ៣ ជីវភាពប្រជាជននៅសហគមន៍ខ្ញុំ",
    "lessonTitleKm": "មេរៀនទី ៧ អ្នកដឹកនាំភូមិខ្ញុំ (និយមន័យភូមិ និងតួនាទីមេភូមិ)",
    "lessonTitleEn": "Lesson 7: Village Leadership - Village Chief Roles",
    "objectivesKm": "ប្រាប់ពីនិយមន័យភូមិ ប្រាប់ឈ្មោះអ្នកដឹកនាំភូមិ និងតួនាទីរបស់មេភូមិ",
    "hoursCount": 3,
    "semester": 2,
    "status": "upcoming",
    "pageSs": "84-85"
  },

  # សីហា (Aug)
  {
    "id": "soc_g3_w36_01",
    "weekNumber": 36,
    "monthKm": "សីហា",
    "subjectId": "sub_social",
    "chapterKm": "ជំពូកទី ៤ ពិភពនៅជុំវិញខ្ញុំ",
    "lessonTitleKm": "មេរៀនទី ១ ទង់ជាតិ & មេរៀនទី ២ យើងត្រូវការកម្តៅ និងពន្លឺ",
    "lessonTitleEn": "Chapter 4 Lesson 1-2: National Flags & Heat and Light Energy",
    "objectivesKm": "រៀបរាប់ទង់ជាតិកម្ពុជា ប្រទេសជិតខាង និងស្គាល់និយមន័យថាមពលកម្តៅនិងពន្លឺ",
    "hoursCount": 4,
    "semester": 2,
    "status": "upcoming",
    "pageSs": "88-94"
  },
  {
    "id": "soc_g3_w36_02",
    "weekNumber": 36,
    "monthKm": "សីហា",
    "subjectId": "sub_social",
    "chapterKm": "ជំពូកទី ៤ ពិភពនៅជុំវិញខ្ញុំ",
    "lessonTitleKm": "មេរៀនទី ៣-៥៖ សូរសំឡេង ផែនដី និងការផ្លាស់ប្តូរធាតុអាកាស (រៀនសារឡើងវិញ)",
    "lessonTitleEn": "Lessons 3-5: Sound, The Earth & Weather Changes (Year-End Review)",
    "objectivesKm": "ស្គាល់សូរសំឡេង ចលនាផែនដី ថ្ងៃនិងយប់ បម្រែបម្រួលធាតុអាកាស និងរំលឹកមេរៀនពេញមួយឆ្នាំ",
    "hoursCount": 6,
    "semester": 2,
    "status": "upcoming",
    "pageSs": "96-108",
    "notes": "រៀនសារឡើងវិញ / ប្រឡងឆមាសទី២"
  }
]

make_social_file(
  'src/data/curriculumSocialGrade3.ts',
  'CURRICULUM_SOCIAL_GRADE3',
  'prog_social_g3',
  3,
  'កម្មវិធីសិក្សាសង្គម ថ្នាក់ទី៣ (MoEYS)',
  'Social Studies Grade 3 Curriculum',
  g3_lessons
)

print("Grade 3 Social Studies built successfully!")
