import json
from generate_social_data import make_social_file

g5_lessons = [
  # វិច្ឆិកា (Nov)
  {
    "id": "soc_g5_w03_01",
    "weekNumber": 3,
    "monthKm": "វិច្ឆិកា",
    "subjectId": "sub_social",
    "chapterKm": "រំលឹកឡើងវិញ",
    "lessonTitleKm": "រំលឹកឡើងវិញមេរៀនសិក្សាសង្គម ថ្នាក់ទី៤ (សប្តាហ៍ទី៣)",
    "lessonTitleEn": "Revision of Grade 4 Social Studies (Week 3)",
    "objectivesKm": "រំលឹកឡើងវិញនូវមូលដ្ឋានគ្រឹះនៃមុខវិជ្ជាសិក្សាសង្គមថ្នាក់ទី៤",
    "hoursCount": 4,
    "semester": 1,
    "status": "completed",
    "pageSs": "1",
    "notes": "រំលឹកឡើងវិញ"
  },
  {
    "id": "soc_g5_w04_01",
    "weekNumber": 4,
    "monthKm": "វិច្ឆិកា",
    "subjectId": "sub_social",
    "chapterKm": "រំលឹកឡើងវិញ",
    "lessonTitleKm": "រំលឹកឡើងវិញមេរៀនសិក្សាសង្គម ថ្នាក់ទី៤ (សប្តាហ៍ទី៤)",
    "lessonTitleEn": "Revision of Grade 4 Social Studies (Week 4)",
    "objectivesKm": "ពង្រឹងចំណេះដឹងត្រៀមចូលមេរៀនថ្នាក់ទី៥",
    "hoursCount": 4,
    "semester": 1,
    "status": "completed",
    "pageSs": "1",
    "notes": "រំលឹកឡើងវិញ"
  },

  # ធ្នូ (Dec)
  {
    "id": "soc_g5_w05_01",
    "weekNumber": 5,
    "monthKm": "ធ្នូ",
    "subjectId": "sub_social",
    "chapterKm": "ជំពូកទី ១ សីលធម៌ និងពលរដ្ឋវិជ្ជា",
    "lessonTitleKm": "មេរៀនទី ១ សហប្រតិបត្តិការ (ក. សហប្រតិបត្តិការក្នុងគ្រួសារ)",
    "lessonTitleEn": "Chapter 1 Lesson 1: Cooperation - Family Cooperation",
    "objectivesKm": "បង្ហាញពីសកម្មភាពសហការក្នុងគ្រួសារ និងផលប្រយោជន៍នៃសហប្រតិបត្តិការ",
    "hoursCount": 2,
    "semester": 1,
    "status": "completed",
    "pageSs": "2-3"
  },
  {
    "id": "soc_g5_w05_02",
    "weekNumber": 5,
    "monthKm": "ធ្នូ",
    "subjectId": "sub_social",
    "chapterKm": "ជំពូកទី ១ សីលធម៌ និងពលរដ្ឋវិជ្ជា",
    "lessonTitleKm": "មេរៀនទី ១ សហប្រតិបត្តិការ (ខ. សហប្រតិបត្តិការក្នុងសាលារៀន)",
    "lessonTitleEn": "Lesson 1: School Cooperation",
    "objectivesKm": "ចូលរួមសហការក្នុងការងារសាលារៀន និងកិច្ចការថ្នាក់",
    "hoursCount": 2,
    "semester": 1,
    "status": "completed",
    "pageSs": "4"
  },
  {
    "id": "soc_g5_w06_01",
    "weekNumber": 6,
    "monthKm": "ធ្នូ",
    "subjectId": "sub_social",
    "chapterKm": "ជំពូកទី ១ សីលធម៌ និងពលរដ្ឋវិជ្ជា",
    "lessonTitleKm": "មេរៀនទី ១ សហប្រតិបត្តិការ (គ. សហប្រតិបត្តិការក្នុងសហគមន៍ & ឃ. ក្នុងប្រទេស)",
    "lessonTitleEn": "Lesson 1: Community & National Cooperation",
    "objectivesKm": "បង្ហាញសកម្មភាពសហការគ្នាក្នុងសហគមន៍ និងក្នុងប្រទេស",
    "hoursCount": 4,
    "semester": 1,
    "status": "completed",
    "pageSs": "5-8"
  },
  {
    "id": "soc_g5_w07_01",
    "weekNumber": 7,
    "monthKm": "ធ្នូ",
    "subjectId": "sub_social",
    "chapterKm": "ជំពូកទី ១ សីលធម៌ និងពលរដ្ឋវិជ្ជា",
    "lessonTitleKm": "មេរៀនទី ២ ទំនាក់ទំនងល្អ (ក. ទំនាក់ទំនងក្នុងគ្រួសារ & ខ. ទំនាក់ទំនងក្នុងសាលារៀន)",
    "lessonTitleEn": "Lesson 2: Good Relationships - Family & School",
    "objectivesKm": "រៀបរាប់ពីទំនាក់ទំនងល្អក្នុងគ្រួសារ និងការប្រាស្រ័យទាក់ទងល្អនៅសាលារៀន",
    "hoursCount": 4,
    "semester": 1,
    "status": "completed",
    "pageSs": "10-13"
  },
  {
    "id": "soc_g5_w08_01",
    "weekNumber": 8,
    "monthKm": "ធ្នូ",
    "subjectId": "sub_social",
    "chapterKm": "ជំពូកទី ១ សីលធម៌ និងពលរដ្ឋវិជ្ជា",
    "lessonTitleKm": "មេរៀនទី ២ ទំនាក់ទំនងល្អ (គ. ទំនាក់ទំនងក្នុងសង្គម) & មេរៀនទី ៣ ការដោះស្រាយទំនាស់ដោយសន្តិវិធី",
    "lessonTitleEn": "Lesson 2-3: Social Relationships & Peaceful Conflict Resolution",
    "objectivesKm": "បង្ហាញទំនាក់ទំនងល្អក្នុងសង្គម និងយល់ដឹងពីវិធីដោះស្រាយទំនាស់ដោយសន្តិវិធី",
    "hoursCount": 4,
    "semester": 1,
    "status": "completed",
    "pageSs": "14-18"
  },

  # មករា (Jan)
  {
    "id": "soc_g5_w09_01",
    "weekNumber": 9,
    "monthKm": "មករា",
    "subjectId": "sub_social",
    "chapterKm": "ជំពូកទី ១ សីលធម៌ និងពលរដ្ឋវិជ្ជា",
    "lessonTitleKm": "មេរៀនទី ៣ ការដោះស្រាយទំនាស់ដោយសន្តិវិធី (ជំហានដោះស្រាយទំនាស់ & ការសម្របសម្រួល)",
    "lessonTitleEn": "Lesson 3: Conflict Resolution Steps & Mediation",
    "objectivesKm": "អនុវត្តជំហានដោះស្រាយទំនាស់ដោយសន្តិវិធី និងការស្វែងរកអ្នកសម្រុះសម្រួល",
    "hoursCount": 4,
    "semester": 1,
    "status": "completed",
    "pageSs": "19-21"
  },
  {
    "id": "soc_g5_w10_01",
    "weekNumber": 10,
    "monthKm": "មករា",
    "subjectId": "sub_social",
    "chapterKm": "ជំពូកទី ១ សីលធម៌ និងពលរដ្ឋវិជ្ជា",
    "lessonTitleKm": "មេរៀនទី ៤ សិទ្ធិកុមារ (ក. សិទ្ធិរស់រានមានជីវិត & ខ. សិទ្ធិទទួលបានការអភិវឌ្ឍ)",
    "lessonTitleEn": "Lesson 4: Child Rights - Right to Survival & Development",
    "objectivesKm": "យល់ច្បាស់ពីសិទ្ធិរស់រានមានជីវិត និងសិទ្ធិទទួលបានការអប់រំនិងការអភិវឌ្ឍ",
    "hoursCount": 4,
    "semester": 1,
    "status": "completed",
    "pageSs": "22-25"
  },
  {
    "id": "soc_g5_w11_01",
    "weekNumber": 11,
    "monthKm": "មករា",
    "subjectId": "sub_social",
    "chapterKm": "ជំពូកទី ១ សីលធម៌ និងពលរដ្ឋវិជ្ជា",
    "lessonTitleKm": "មេរៀនទី ៤ សិទ្ធិកុមារ (គ. សិទ្ធិទទួលបានការការពារ & ឃ. សិទ្ធិចូលរួម)",
    "lessonTitleEn": "Lesson 4: Child Rights - Right to Protection & Participation",
    "objectivesKm": "ស្គាល់ពីសិទ្ធិទទួលបានការការពារពីអំពើហិង្សា និងសិទ្ធិក្នុងការបញ្ចេញមតិ",
    "hoursCount": 4,
    "semester": 1,
    "status": "completed",
    "pageSs": "26-29"
  },
  {
    "id": "soc_g5_w12_01",
    "weekNumber": 12,
    "monthKm": "មករា",
    "subjectId": "sub_social",
    "chapterKm": "ជំពូកទី ២ សុវត្ថិភាពចរាចរណ៍ និងការការពារខ្លួន",
    "lessonTitleKm": "មេរៀនទី ១ សុវត្ថិភាពចរាចរណ៍ផ្លូវគោក (ក. ភ្លើងសញ្ញានិងស្លាកសញ្ញាចរាចរណ៍)",
    "lessonTitleEn": "Chapter 2 Lesson 1: Road Safety - Traffic Lights & Signs",
    "objectivesKm": "សម្គាល់និងយល់ពីអត្ថន័យនៃស្លាកសញ្ញា និងភ្លើងសញ្ញាចរាចរណ៍នានា",
    "hoursCount": 4,
    "semester": 1,
    "status": "completed",
    "pageSs": "32-35"
  },

  # កុម្ភៈ (Feb)
  {
    "id": "soc_g5_w13_01",
    "weekNumber": 13,
    "monthKm": "កុម្ភៈ",
    "subjectId": "sub_social",
    "chapterKm": "ជំពូកទី ២ សុវត្ថិភាពចរាចរណ៍ និងការការពារខ្លួន",
    "lessonTitleKm": "មេរៀនទី ១ សុវត្ថិភាពចរាចរណ៍ផ្លូវគោក (ខ. ការបើកបរប្រកបដោយសុវត្ថិភាព)",
    "lessonTitleEn": "Lesson 1: Safe Driving Practices & Pedestrian Rules",
    "objectivesKm": "គោរពច្បាប់ចរាចរណ៍ និងការធ្វើដំណើរដោយសុវត្ថិភាពសម្រាប់អ្នកថ្មើរជើងនិងអ្នកជិះកង់",
    "hoursCount": 4,
    "semester": 1,
    "status": "in_progress",
    "pageSs": "36-39"
  },
  {
    "id": "soc_g5_w14_01",
    "weekNumber": 14,
    "monthKm": "កុម្ភៈ",
    "subjectId": "sub_social",
    "chapterKm": "ជំពូកទី ២ សុវត្ថិភាពចរាចរណ៍ និងការការពារខ្លួន",
    "lessonTitleKm": "មេរៀនទី ២ ការការពារខ្លួនពីការរំលោភបំពាន (ក. ទម្រង់ផ្សេងៗនៃការរំលោភបំពាន)",
    "lessonTitleEn": "Lesson 2: Self-Protection Against Abuse - Forms of Abuse",
    "objectivesKm": "កំណត់ទម្រង់ផ្សេងៗនៃការរំលោភបំពានលើកុមារ",
    "hoursCount": 4,
    "semester": 1,
    "status": "in_progress",
    "pageSs": "40-43"
  },
  {
    "id": "soc_g5_w15_01",
    "weekNumber": 15,
    "monthKm": "កុម្ភៈ",
    "subjectId": "sub_social",
    "chapterKm": "ជំពូកទី ២ សុវត្ថិភាពចរាចរណ៍ និងការការពារខ្លួន",
    "lessonTitleKm": "មេរៀនទី ២ ការការពារខ្លួនពីការរំលោភបំពាន (ខ. វិធីការពារខ្លួន & គ. កន្លែងស្វែងរកជំនួយ)",
    "lessonTitleEn": "Lesson 2: Protection Skills & Seeking Help Hotlines",
    "objectivesKm": "អនុវត្តវិធីការពារខ្លួន និងស្គាល់បណ្តាញស្វែងរកជំនួយពេលជួបគ្រោះថ្នាក់",
    "hoursCount": 4,
    "semester": 1,
    "status": "in_progress",
    "pageSs": "44-47"
  },
  {
    "id": "soc_g5_w16_01",
    "weekNumber": 16,
    "monthKm": "កុម្ភៈ",
    "subjectId": "sub_social",
    "chapterKm": "ជំពូកទី ៣ ប្រវត្តិវិទ្យា (ប្រវត្តិសាស្ត្រខ្មែរ)",
    "lessonTitleKm": "មេរៀនទី ១ ប្រទេសកម្ពុជាសម័យអង្គរ (ក. ការកកើតសម័យអង្គរ)",
    "lessonTitleEn": "Chapter 3 Lesson 1: Angkor Empire - Rise of Angkor Era",
    "objectivesKm": "រៀបរាប់ពីការបង្រួបបង្រួមជាតិ និងការឡើងគ្រងរាជ្យរបស់ព្រះបាទជ័យវរ្ម័នទី២",
    "hoursCount": 4,
    "semester": 1,
    "status": "in_progress",
    "pageSs": "50-53"
  },

  # មីនា (Mar)
  {
    "id": "soc_g5_w17_01",
    "weekNumber": 17,
    "monthKm": "មីនា",
    "subjectId": "sub_social",
    "chapterKm": "ជំពូកទី ៣ ប្រវត្តិវិទ្យា (ប្រវត្តិសាស្ត្រខ្មែរ)",
    "lessonTitleKm": "មេរៀនទី ១ ប្រទេសកម្ពុជាសម័យអង្គរ (ខ. ព្រះបាទសូរ្យវរ្ម័នទី២ & ប្រាសាទអង្គរវត្ត)",
    "lessonTitleEn": "Lesson 1: King Suryavarman II & Angkor Wat Temple",
    "objectivesKm": "ពណ៌នាអំពីស្នាព្រះហស្តព្រះបាទសូរ្យវរ្ម័នទី២ និងការកសាងប្រាសាទអង្គរវត្ត",
    "hoursCount": 4,
    "semester": 1,
    "status": "upcoming",
    "pageSs": "54-57"
  },
  {
    "id": "soc_g5_w18_01",
    "weekNumber": 18,
    "monthKm": "មីនា",
    "subjectId": "sub_social",
    "chapterKm": "ជំពូកទី ៣ ប្រវត្តិវិទ្យា (ប្រវត្តិសាស្ត្រខ្មែរ)",
    "lessonTitleKm": "មេរៀនទី ១ ប្រទេសកម្ពុជាសម័យអង្គរ (គ. ព្រះបាទជ័យវរ្ម័នទី៧ & ប្រឡងឆមាសទី១)",
    "lessonTitleEn": "Lesson 1: King Jayavarman VII & Semester 1 Examination",
    "objectivesKm": "ពណ៌នាពីស្នាព្រះហស្តព្រះបាទជ័យវរ្ម័នទី៧ ប្រាសាទបាយ័ន មន្ទីរពេទ្យ និងប្រឡងឆមាសទី១",
    "hoursCount": 4,
    "semester": 1,
    "status": "upcoming",
    "isExamOrHoliday": True,
    "pageSs": "58-61",
    "notes": "ប្រឡងឆមាសទី១"
  },

  # Semester 2
  {
    "id": "soc_g5_w19_01",
    "weekNumber": 19,
    "monthKm": "មីនា",
    "subjectId": "sub_social",
    "chapterKm": "ជំពូកទី ៣ ប្រវត្តិវិទ្យា (ប្រវត្តិសាស្ត្រខ្មែរ)",
    "lessonTitleKm": "មេរៀនទី ២ អរិយធម៌សម័យអង្គរ (ក. រដ្ឋបាល & សេដ្ឋកិច្ចសម័យអង្គរ)",
    "lessonTitleEn": "Lesson 2: Angkor Civilization - Administration & Agriculture",
    "objectivesKm": "រៀបរាប់ពីរចនាសម្ព័ន្ធរដ្ឋបាល ប្រព័ន្ធធារាសាស្ត្រ និងកសិកម្មសម័យអង្គរ",
    "hoursCount": 4,
    "semester": 2,
    "status": "upcoming",
    "pageSs": "64-67"
  },
  {
    "id": "soc_g5_w20_01",
    "weekNumber": 20,
    "monthKm": "មីនា",
    "subjectId": "sub_social",
    "chapterKm": "ជំពូកទី ៣ ប្រវត្តិវិទ្យា (ប្រវត្តិសាស្ត្រខ្មែរ)",
    "lessonTitleKm": "មេរៀនទី ២ អរិយធម៌សម័យអង្គរ (ខ. សាសនា សិល្បៈ និងស្ថាបត្យកម្ម)",
    "lessonTitleEn": "Lesson 2: Religion, Art & Monumental Architecture of Angkor",
    "objectivesKm": "បង្ហាញពីជំនឿសាសនា ព្រហ្មញ្ញសាសនា ព្រះពុទ្ធសាសនា និងស្ថាបត្យកម្មប្រាសាទបុរាណ",
    "hoursCount": 4,
    "semester": 2,
    "status": "upcoming",
    "pageSs": "68-71"
  },

  # មេសា (Apr)
  {
    "id": "soc_g5_w21_01",
    "weekNumber": 21,
    "monthKm": "មេសា",
    "subjectId": "sub_social",
    "chapterKm": "ជំពូកទី ៤ ភូមិវិទ្យាប្រទេសកម្ពុជា",
    "lessonTitleKm": "មេរៀនទី ១ ទីតាំង ព្រំប្រទល់ និងទំហំប្រទេសកម្ពុជា (ក. ទីតាំងភូមិសាស្ត្រ)",
    "lessonTitleEn": "Chapter 4 Lesson 1: Geography of Cambodia - Location & Borders",
    "objectivesKm": "កំណត់ទីតាំងភូមិសាស្ត្រ ព្រំប្រទល់ជាប់ប្រទេសជិតខាង និងទំហំផ្ទៃដីប្រទេសកម្ពុជា",
    "hoursCount": 4,
    "semester": 2,
    "status": "upcoming",
    "pageSs": "74-77"
  },
  {
    "id": "soc_g5_w24_01",
    "weekNumber": 24,
    "monthKm": "មេសា",
    "subjectId": "sub_social",
    "chapterKm": "ជំពូកទី ៤ ភូមិវិទ្យាប្រទេសកម្ពុជា",
    "lessonTitleKm": "មេរៀនទី ១ ទីតាំង ព្រំប្រទល់ និងទំហំប្រទេសកម្ពុជា (ខ. ការគូសផែនទីប្រទេសកម្ពុជា)",
    "lessonTitleEn": "Lesson 1: Map Drawing of Cambodia & Boundary Lines",
    "objectivesKm": "អនុវត្តគូសផែនទីប្រទេសកម្ពុជា និងសម្គាល់ព្រំប្រទល់ខេត្តសំខាន់ៗ",
    "hoursCount": 4,
    "semester": 2,
    "status": "upcoming",
    "pageSs": "78-80"
  },

  # ឧសភា (May)
  {
    "id": "soc_g5_w25_01",
    "weekNumber": 25,
    "monthKm": "ឧសភា",
    "subjectId": "sub_social",
    "chapterKm": "ជំពូកទី ៤ ភូមិវិទ្យាប្រទេសកម្ពុជា",
    "lessonTitleKm": "មេរៀនទី ២ ទម្រង់ដីប្រទេសកម្ពុជា (ក. តំបន់វាលទំនាបកណ្តាល)",
    "lessonTitleEn": "Lesson 2: Landforms of Cambodia - Central Lowland Plains",
    "objectivesKm": "រៀបរាប់ពីលក្ខណៈភូមិសាស្ត្រ និងសក្តានុពលកសិកម្មនៃតំបន់វាលទំនាប",
    "hoursCount": 4,
    "semester": 2,
    "status": "upcoming",
    "pageSs": "82-85"
  },
  {
    "id": "soc_g5_w26_01",
    "weekNumber": 26,
    "monthKm": "ឧសភា",
    "subjectId": "sub_social",
    "chapterKm": "ជំពូកទី ៤ ភូមិវិទ្យាប្រទេសកម្ពុជា",
    "lessonTitleKm": "មេរៀនទី ២ ទម្រង់ដីប្រទេសកម្ពុជា (ខ. តំបន់បឹងទន្លេសាប)",
    "lessonTitleEn": "Lesson 2: Tonle Sap Lake & Biosphere Reserve",
    "objectivesKm": "ពណ៌នាអំពីសារៈសំខាន់នៃបឹងទន្លេសាប មច្ឆាជាតិ និងជីវចម្រុះ",
    "hoursCount": 4,
    "semester": 2,
    "status": "upcoming",
    "pageSs": "86-89"
  },
  {
    "id": "soc_g5_w27_01",
    "weekNumber": 27,
    "monthKm": "ឧសភា",
    "subjectId": "sub_social",
    "chapterKm": "ជំពូកទី ៤ ភូមិវិទ្យាប្រទេសកម្ពុជា",
    "lessonTitleKm": "មេរៀនទី ២ ទម្រង់ដីប្រទេសកម្ពុជា (គ. តំបន់ខ្ពង់រាប និងជួរភ្នំ)",
    "lessonTitleEn": "Lesson 2: Plateaus & Mountain Ranges (Cardamom & Dangrek)",
    "objectivesKm": "កំណត់ទីតាំងជួរភ្នំក្រវាញ ជួរភ្នំដងរែក និងខ្ពង់រាបភាគឦសាន",
    "hoursCount": 4,
    "semester": 2,
    "status": "upcoming",
    "pageSs": "90-93"
  },
  {
    "id": "soc_g5_w28_01",
    "weekNumber": 28,
    "monthKm": "ឧសភា",
    "subjectId": "sub_social",
    "chapterKm": "ជំពូកទី ៤ ភូមិវិទ្យាប្រទេសកម្ពុជា",
    "lessonTitleKm": "មេរៀនទី ២ ទម្រង់ដីប្រទេសកម្ពុជា (ឃ. តំបន់ឆ្នេរសមុទ្រ)",
    "lessonTitleEn": "Lesson 2: Coastal Region & Marine Resources",
    "objectivesKm": "រៀបរាប់ពីខេត្តតំបន់ឆ្នេរ ធនធានសមុទ្រ និងវិស័យទេសចរណ៍",
    "hoursCount": 4,
    "semester": 2,
    "status": "upcoming",
    "pageSs": "94-97"
  },

  # មិថុនា (Jun)
  {
    "id": "soc_g5_w29_01",
    "weekNumber": 29,
    "monthKm": "មិថុនា",
    "subjectId": "sub_social",
    "chapterKm": "ជំពូកទី ៤ ភូមិវិទ្យាប្រទេសកម្ពុជា",
    "lessonTitleKm": "មេរៀនទី ៣ អាកាសធាតុប្រទេសកម្ពុជា (ក. រដូវប្រាំង & ខ. រដូវវស្សា)",
    "lessonTitleEn": "Lesson 3: Climate of Cambodia - Dry & Rainy Seasons (Monsoon)",
    "objectivesKm": "ពន្យល់ពីឥទ្ធិពលខ្យល់មូសុង និងលក្ខណៈនៃរដូវប្រាំងនិងរដូវវស្សា",
    "hoursCount": 4,
    "semester": 2,
    "status": "upcoming",
    "pageSs": "100-103"
  },
  {
    "id": "soc_g5_w30_01",
    "weekNumber": 30,
    "monthKm": "មិថុនា",
    "subjectId": "sub_social",
    "chapterKm": "ជំពូកទី ៤ ភូមិវិទ្យាប្រទេសកម្ពុជា",
    "lessonTitleKm": "មេរៀនទី ៤ ធនធានធម្មជាតិ (ក. ធនធានទឹក និងធនធានរ៉ែ)",
    "lessonTitleEn": "Lesson 4: Natural Resources - Water & Mineral Resources",
    "objectivesKm": "រៀបរាប់ពីប្រព័ន្ធទន្លេមេគង្គ ធនធានទឹក និងធនធានរ៉ែក្នុងដី",
    "hoursCount": 4,
    "semester": 2,
    "status": "upcoming",
    "pageSs": "104-107"
  },
  {
    "id": "soc_g5_w31_01",
    "weekNumber": 31,
    "monthKm": "មិថុនា",
    "subjectId": "sub_social",
    "chapterKm": "ជំពូកទី ៤ ភូមិវិទ្យាប្រទេសកម្ពុជា",
    "lessonTitleKm": "មេរៀនទី ៤ ធនធានធម្មជាតិ (ខ. ធនធានព្រៃឈើ និងសត្វព្រៃ)",
    "lessonTitleEn": "Lesson 4: Natural Resources - Forests & Wildlife Protection",
    "objectivesKm": "ស្គាល់តម្លៃព្រៃឈើ សត្វព្រៃ និងការចូលរួមការពារធនធានធម្មជាតិ",
    "hoursCount": 4,
    "semester": 2,
    "status": "upcoming",
    "pageSs": "108-111"
  },
  {
    "id": "soc_g5_w32_01",
    "weekNumber": 32,
    "monthKm": "មិថុនា",
    "subjectId": "sub_social",
    "chapterKm": "ជំពូកទី ៥ សិល្បៈ និងវប្បធម៌ខ្មែរ",
    "lessonTitleKm": "មេរៀនទី ១ ចម្រៀង និងតន្ត្រីខ្មែរ (ក. ភ្លេងពិណពាទ្យ និងភ្លេងមហោរី)",
    "lessonTitleEn": "Chapter 5 Lesson 1: Traditional Music - Pinpeat & Mohori Orchestras",
    "objectivesKm": "ស្គាល់ឧបករណ៍តន្ត្រីបុរាណ និងវង់ភ្លេងពិណពាទ្យ ព្រមទាំងវង់ភ្លេងមហោរី",
    "hoursCount": 4,
    "semester": 2,
    "status": "upcoming",
    "pageSs": "114-117"
  },

  # កក្កដា (Jul)
  {
    "id": "soc_g5_w33_01",
    "weekNumber": 33,
    "monthKm": "កក្កដា",
    "subjectId": "sub_social",
    "chapterKm": "ជំពូកទី ៥ សិល្បៈ និងវប្បធម៌ខ្មែរ",
    "lessonTitleKm": "មេរៀនទី ២ របាំប្រពៃណី និងរបាំបុរាណ (ក. របាំព្រះរាជទ្រព្យ និងរបាំប្រជាប្រិយ)",
    "lessonTitleEn": "Lesson 2: Royal Ballet & Folk Dances (Robam)",
    "objectivesKm": "រៀបរាប់ពីលក្ខណៈនៃរបាំព្រះរាជទ្រព្យ និងរបាំប្រជាប្រិយខ្មែរ",
    "hoursCount": 4,
    "semester": 2,
    "status": "upcoming",
    "pageSs": "118-121"
  },
  {
    "id": "soc_g5_w34_01",
    "weekNumber": 34,
    "monthKm": "កក្កដា",
    "subjectId": "sub_social",
    "chapterKm": "ជំពូកទី ៥ សិល្បៈ និងវប្បធម៌ខ្មែរ",
    "lessonTitleKm": "មេរៀនទី ៣ គំនូរ និងចម្លាក់ខ្មែរ (ក. ក្បាច់ភ្ញីទេស ភ្ញីអង្គរ និងចម្លាក់ថ្ម)",
    "lessonTitleEn": "Lesson 3: Khmer Painting & Stone Relief Sculptures",
    "objectivesKm": "ហាត់គូររូបក្បាច់ខ្មែរ និងស្គាល់ស្នាដៃចម្លាក់ថ្មនៅតាមប្រាសាទបុរាណ",
    "hoursCount": 4,
    "semester": 2,
    "status": "upcoming",
    "pageSs": "122-125"
  },
  {
    "id": "soc_g5_w35_01",
    "weekNumber": 35,
    "monthKm": "កក្កដា",
    "subjectId": "sub_social",
    "chapterKm": "ជំពូកទី ៥ សិល្បៈ និងវប្បធម៌ខ្មែរ",
    "lessonTitleKm": "មេរៀនទី ៤ សិល្បៈហត្ថកម្ម (ក. តម្បាញសូត្រ គ្រឿងប្រាក់ និងស្មូនដី)",
    "lessonTitleEn": "Lesson 4: Handicrafts - Silk Weaving, Silverware & Pottery",
    "objectivesKm": "រៀបរាប់ពីផលិតផលហត្ថកម្មបុរាណខ្មែរ និងសារៈសំខាន់សម្រាប់ជីវភាពសហគមន៍",
    "hoursCount": 4,
    "semester": 2,
    "status": "upcoming",
    "pageSs": "126-129"
  },

  # សីហា (Aug)
  {
    "id": "soc_g5_w36_01",
    "weekNumber": 36,
    "monthKm": "សីហា",
    "subjectId": "sub_social",
    "chapterKm": "រៀនសារឡើងវិញ និងប្រឡងឆមាសទី២",
    "lessonTitleKm": "រៀនសារឡើងវិញមេរៀនសិក្សាសង្គម ថ្នាក់ទី៥ ទាំងមូល",
    "lessonTitleEn": "Comprehensive Revision of Grade 5 Social Studies",
    "objectivesKm": "រំលឹកឡើងវិញនូវចំណេះដឹងសីលធម៌ ប្រវត្តិវិទ្យា ភូមិវិទ្យា និងសិល្បៈ",
    "hoursCount": 4,
    "semester": 2,
    "status": "upcoming",
    "notes": "រៀនសារឡើងវិញ"
  },
  {
    "id": "soc_g5_w36_02",
    "weekNumber": 36,
    "monthKm": "សីហា",
    "subjectId": "sub_social",
    "chapterKm": "រៀនសារឡើងវិញ និងប្រឡងឆមាសទី២",
    "lessonTitleKm": "ការប្រឡងបញ្ចប់ឆ្នាំសិក្សា (ឆមាសទី២)",
    "lessonTitleEn": "Final Year Examination (Semester 2)",
    "objectivesKm": "វាយតម្លៃកម្រិតយល់ដឹង និងលទ្ធផលសិក្សារបស់សិស្សប្រចាំឆ្នាំ",
    "hoursCount": 4,
    "semester": 2,
    "status": "upcoming",
    "isExamOrHoliday": True,
    "notes": "ប្រឡងឆមាសទី២"
  }
]

make_social_file(
  'src/data/curriculumSocialGrade5.ts',
  'CURRICULUM_SOCIAL_GRADE5',
  'prog_social_g5',
  5,
  'កម្មវិធីសិក្សាសង្គម ថ្នាក់ទី៥ (MoEYS)',
  'Social Studies Grade 5 Curriculum',
  g5_lessons
)

print("Grade 5 Social Studies built successfully!")
