#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import json

def get_grade1_lessons():
    return [
        # === ខែវិច្ឆិកា (November) ===
        # សប្តាហ៍ទី១
        {"id": "g1_kh_1", "weekNumber": 1, "subjectId": "sub_khmer", "monthKm": "វិច្ឆិកា", "dateStr": "សៅរ៍_01-11-25", "chapterKm": "ដើមឆ្នាំសិក្សា", "lessonTitleKm": "ថ្ងៃបើកបវេសនកាល", "lessonTitleEn": "School Opening Day", "objectivesKm": "ការបើកបវេសនកាលឆ្នាំសិក្សាថ្មី និងស្វាគមន៍សិស្សានុសិស្ស។", "hoursCount": 1, "semester": 1, "status": "completed", "isExamOrHoliday": True, "notes": "ថ្ងៃបើកបវេសនកាល"},
        {"id": "g1_kh_2", "weekNumber": 1, "subjectId": "sub_khmer", "monthKm": "វិច្ឆិកា", "dateStr": "ចន្ទ_03-11-25", "chapterKm": "ត្រៀមរៀនអក្សរ", "lessonNumber": 1, "lessonTitleKm": "១.រៀនគូសបន្ទាត់", "lessonTitleEn": "1. Practice Line Drawing", "objectivesKm": "ហ្វឹកហាត់សម្របសម្រួលរវាងចលនាភ្នែកនិងចលនាដៃក្នុងការគូសបន្ទាត់ដើម្បីត្រៀមសរសេរតួអក្សរ", "hoursCount": 2, "semester": 1, "status": "completed"},
        {"id": "g1_kh_3", "weekNumber": 1, "subjectId": "sub_khmer", "monthKm": "វិច្ឆិកា", "dateStr": "ចន្ទ_03-11-25", "chapterKm": "ម៉ោងបត់បែន", "lessonTitleKm": "ម៉ោងបត់បែន", "lessonTitleEn": "Flexible Hour", "objectivesKm": "ពង្រឹងការហ្វឹកហាត់ចលនាដៃ និងកាយវិការសរសេររបស់សិស្ស", "hoursCount": 1, "semester": 1, "status": "completed", "notes": "ម៉ោងបត់បែន"},
        {"id": "g1_kh_4", "weekNumber": 1, "subjectId": "sub_khmer", "monthKm": "វិច្ឆិកា", "dateStr": "អង្គារ_04-11-25 ដល់ ព្រហ_06-11-25", "chapterKm": "បុណ្យជាតិ", "lessonTitleKm": "ព្រះរាជពិធីបុណ្យអុំទូក បណ្តែតប្រទីប និងសំពះព្រះខែ អកអំបុក", "lessonTitleEn": "Water Festival Holiday", "objectivesKm": "ឈប់សម្រាកព្រះរាជពិធីបុណ្យអុំទូក បណ្តែតប្រទីប និងសំពះព្រះខែ អកអំបុក", "hoursCount": 0, "semester": 1, "status": "completed", "isExamOrHoliday": True, "notes": "ព្រះរាជពិធីបុណ្យអុំទូក"},
        {"id": "g1_kh_5", "weekNumber": 1, "subjectId": "sub_khmer", "monthKm": "វិច្ឆិកា", "dateStr": "សុក្រ_07-11-25", "chapterKm": "ត្រៀមរៀនអក្សរ", "lessonNumber": 2, "lessonTitleKm": "២.រៀនគូសបន្ទាត់", "lessonTitleEn": "2. Practice Line Drawing", "objectivesKm": "ហ្វឹកហាត់សម្របសម្រួលរវាងចលនាភ្នែកនិងចលនាដៃក្នុងការគូសបន្ទាត់ដើម្បីត្រៀមសរសេរតួអក្សរ", "hoursCount": 2, "semester": 1, "status": "completed"},
        {"id": "g1_kh_6", "weekNumber": 1, "subjectId": "sub_khmer", "monthKm": "វិច្ឆិកា", "dateStr": "សុក្រ_07-11-25", "chapterKm": "ម៉ោងបត់បែន", "lessonTitleKm": "ម៉ោងបត់បែន", "lessonTitleEn": "Flexible Hour", "objectivesKm": "ហ្វឹកហាត់សរសេរបន្ទាត់ត្រង់ បន្ទាត់កោង និងរង្វង់", "hoursCount": 1, "semester": 1, "status": "completed", "notes": "ម៉ោងបត់បែន"},
        
        # សប្តាហ៍ទី២
        {"id": "g1_kh_7", "weekNumber": 2, "subjectId": "sub_khmer", "monthKm": "វិច្ឆិកា", "dateStr": "សៅរ៍_08-11-25", "chapterKm": "ស្រៈនិស្ស័យ", "lessonNumber": 3, "lessonTitleKm": "៣.ចម្រៀងស្រៈនិស្ស័យ", "lessonTitleEn": "3. Dependent Vowels Song", "objectivesKm": "ច្រៀងចម្រៀងតាមបែបបទដើម្បីបន្លឺឈ្មោះស្រៈនិស្ស័យបានត្រឹមត្រូវ", "hoursCount": 2, "semester": 1, "status": "completed"},
        {"id": "g1_kh_8", "weekNumber": 2, "subjectId": "sub_khmer", "monthKm": "វិច្ឆិកា", "dateStr": "ចន្ទ_10-11-25", "chapterKm": "ស្រៈនិស្ស័យ", "lessonNumber": 4, "lessonTitleKm": "៤.ចម្រៀងស្រៈនិស្ស័យ", "lessonTitleEn": "4. Dependent Vowels Song (Cont.)", "objectivesKm": "ច្រៀងចម្រៀងតាមបែបបទដើម្បីបន្លឺឈ្មោះស្រៈនិស្ស័យបានត្រឹមត្រូវ", "hoursCount": 2, "semester": 1, "status": "completed"},
        {"id": "g1_kh_9", "weekNumber": 2, "subjectId": "sub_khmer", "monthKm": "វិច្ឆិកា", "dateStr": "ចន្ទ_10-11-25", "chapterKm": "ម៉ោងបត់បែន", "lessonTitleKm": "ម៉ោងបត់បែន", "lessonTitleEn": "Flexible Hour", "objectivesKm": "ពង្រឹងការបន្លឺសូរស្រៈ និងចលនាដៃ", "hoursCount": 1, "semester": 1, "status": "completed", "notes": "ម៉ោងបត់បែន"},
        {"id": "g1_kh_10", "weekNumber": 2, "subjectId": "sub_khmer", "monthKm": "វិច្ឆិកា", "dateStr": "អង្គារ_11-11-25", "chapterKm": "ស្រៈនិស្ស័យ", "lessonNumber": 5, "lessonTitleKm": "៥.ចម្រៀងស្រៈនិស្ស័យ", "lessonTitleEn": "5. Dependent Vowels Song Review", "objectivesKm": "ច្រៀងចម្រៀងតាមបែបបទដើម្បីបន្លឺឈ្មោះស្រៈនិស្ស័យបានត្រឹមត្រូវ", "hoursCount": 2, "semester": 1, "status": "completed"},
        {"id": "g1_kh_11", "weekNumber": 2, "subjectId": "sub_khmer", "monthKm": "វិច្ឆិកា", "dateStr": "ពុធ_12-11-25", "chapterKm": "ព្យញ្ជនៈ", "lessonNumber": 6, "lessonTitleKm": "៦.ចម្រៀងព្យញ្ជនៈ", "lessonTitleEn": "6. Consonants Song", "objectivesKm": "ច្រៀងចម្រៀងតាមបែបបទដើម្បីបន្លឺឈ្មោះព្យញ្ជនៈបានត្រឹមត្រូវ", "hoursCount": 2, "semester": 1, "status": "completed"},
        {"id": "g1_kh_12", "weekNumber": 2, "subjectId": "sub_khmer", "monthKm": "វិច្ឆិកា", "dateStr": "ពុធ_12-11-25", "chapterKm": "ម៉ោងបត់បែន", "lessonTitleKm": "ម៉ោងបត់បែន", "lessonTitleEn": "Flexible Hour", "objectivesKm": "ហ្វឹកហាត់បន្លឺសូរព្យញ្ជនៈទាំង ៣៣ តួ", "hoursCount": 1, "semester": 1, "status": "completed", "notes": "ម៉ោងបត់បែន"},
        {"id": "g1_kh_13", "weekNumber": 2, "subjectId": "sub_khmer", "monthKm": "វិច្ឆិកា", "dateStr": "ព្រហស្បតិ៍_13-11-25", "chapterKm": "បង្រៀនបំប៉ន", "lessonTitleKm": "បង្រៀនបំប៉ន", "lessonTitleEn": "Remedial Teaching", "objectivesKm": "បង្រៀនបំប៉នសិស្សរៀនយឺតលើការគូសបន្ទាត់ និងការបន្លឺសូរអក្សរ", "hoursCount": 1, "semester": 1, "status": "completed", "notes": "បង្រៀនបំប៉ន"},
        {"id": "g1_kh_14", "weekNumber": 2, "subjectId": "sub_khmer", "monthKm": "វិច្ឆិកា", "dateStr": "សុក្រ_14-11-25", "chapterKm": "ព្យញ្ជនៈពួកអ", "lessonNumber": 7, "lessonTitleKm": "៧.ការណែនាំតួអក្សរ ក ខ", "lessonTitleEn": "7. Introduction to Consonants Ka and Kha", "objectivesKm": "កំណត់សូរ កំណត់រូបរាង អាន និងសរសេរព្យញ្ជនៈ ក ខ។ ស្ដាប់រឿងនិទាន និងឆ្លើយសំណួរទាក់ទងនឹងព័ត៌មានបង្ហាញត្រង់និងបង្កប់។", "hoursCount": 2, "semester": 1, "status": "completed", "pageSs": 2},
        {"id": "g1_kh_15", "weekNumber": 2, "subjectId": "sub_khmer", "monthKm": "វិច្ឆិកា", "dateStr": "សុក្រ_14-11-25", "chapterKm": "ម៉ោងបត់បែន", "lessonTitleKm": "ម៉ោងបត់បែន", "lessonTitleEn": "Flexible Hour", "objectivesKm": "ហ្វឹកហាត់សរសេរ ក និង ខ លើក្តារឆ្នួន", "hoursCount": 1, "semester": 1, "status": "completed", "notes": "ម៉ោងបត់បែន"},
        
        # សប្តាហ៍ទី៣
        {"id": "g1_kh_16", "weekNumber": 3, "subjectId": "sub_khmer", "monthKm": "វិច្ឆិកា", "dateStr": "សៅរ៍_15-11-25", "chapterKm": "ព្យញ្ជនៈពួកអ", "lessonNumber": 8, "lessonTitleKm": "៨.ការណែនាំតួអក្សរ ច ឆ", "lessonTitleEn": "8. Introduction to Consonants Cha and Chha", "objectivesKm": "កំណត់សូរ កំណត់រូបរាង អាន និងសរសេរព្យញ្ជនៈ ច ឆ។ ស្ដាប់រឿងនិទាន និងឆ្លើយសំណួរទាក់ទងនឹងព័ត៌មានបង្ហាញត្រង់និងបង្កប់។", "hoursCount": 2, "semester": 1, "status": "completed", "pageSs": 6},
        {"id": "g1_kh_17", "weekNumber": 3, "subjectId": "sub_khmer", "monthKm": "វិច្ឆិកា", "dateStr": "ចន្ទ_17-11-25", "chapterKm": "ស្រៈនិស្ស័យ", "lessonNumber": 9, "lessonTitleKm": "៩.មេរៀនទី២-៤ ស្រៈនិស្ស័យ ា", "lessonTitleEn": "9. Lessons 2-4: Dependent Vowel Aa (ា)", "objectivesKm": "កំណត់សូរ កំណត់រូបរាង អាន និងសរសេរ ស្រៈ«ា»។ អានព្យាង្គ ពាក្យ និងបង្កើតល្បះផ្ទាល់មាត់ ដោយប្រើប្រាស់ពាក្យងាយៗ ដែលមានព្យញ្ជនៈ ក ខ ច ឆ ផ្សំជាមួយស្រៈ«ា»។ អានស្ទាត់និងយល់ន័យអត្ថបទខ្លី។", "hoursCount": 2, "semester": 1, "status": "completed", "pageSs": 10},
        {"id": "g1_kh_18", "weekNumber": 3, "subjectId": "sub_khmer", "monthKm": "វិច្ឆិកា", "dateStr": "ចន្ទ_17-11-25", "chapterKm": "ម៉ោងបត់បែន", "lessonTitleKm": "ម៉ោងបត់បែន", "lessonTitleEn": "Flexible Hour", "objectivesKm": "ហ្វឹកហាត់ផ្សំសូរ កា ខា ចា ឆា", "hoursCount": 1, "semester": 1, "status": "completed", "notes": "ម៉ោងបត់បែន"},
        {"id": "g1_kh_19", "weekNumber": 3, "subjectId": "sub_khmer", "monthKm": "វិច្ឆិកា", "dateStr": "អង្គារ_18-11-25", "chapterKm": "ស្រៈនិស្ស័យ", "lessonNumber": 10, "lessonTitleKm": "១០.មេរៀនទី២-៤ ស្រៈនិស្ស័យ ិ", "lessonTitleEn": "10. Dependent Vowel I (ិ)", "objectivesKm": "កំណត់សូរ កំណត់រូបរាង អាន និងសរសេរ ស្រៈ«ិ»។ អានព្យាង្គ ពាក្យ និងបង្កើតល្បះផ្ទាល់មាត់ ដែលមានព្យញ្ជនៈ ក ខ ច ឆ ផ្សំជាមួយស្រៈ«ិ»។", "hoursCount": 2, "semester": 1, "status": "completed", "pageSs": 12},
        {"id": "g1_kh_20", "weekNumber": 3, "subjectId": "sub_khmer", "monthKm": "វិច្ឆិកា", "dateStr": "ពុធ_19-11-25", "chapterKm": "ស្រៈនិស្ស័យ", "lessonNumber": 11, "lessonTitleKm": "១១.មេរៀនទី២-៤ ស្រៈនិស្ស័យ ី", "lessonTitleEn": "11. Dependent Vowel Ee (ី)", "objectivesKm": "កំណត់សូរ កំណត់រូបរាង អាន និងសរសេរ ស្រៈ«ី»។ អានព្យាង្គ ពាក្យ និងបង្កើតល្បះផ្ទាល់មាត់ ដែលមានព្យញ្ជនៈ ក ខ ច ឆ ផ្សំជាមួយស្រៈ«ី»។", "hoursCount": 2, "semester": 1, "status": "completed", "pageSs": 14},
        {"id": "g1_kh_21", "weekNumber": 3, "subjectId": "sub_khmer", "monthKm": "វិច្ឆិកា", "dateStr": "ពុធ_19-11-25", "chapterKm": "ម៉ោងបត់បែន", "lessonTitleKm": "ម៉ោងបត់បែន", "lessonTitleEn": "Flexible Hour", "objectivesKm": "ហ្វឹកហាត់អានពាក្យ គី ខី ជី ឈី", "hoursCount": 1, "semester": 1, "status": "completed", "notes": "ម៉ោងបត់បែន"},
        {"id": "g1_kh_22", "weekNumber": 3, "subjectId": "sub_khmer", "monthKm": "វិច្ឆិកា", "dateStr": "ព្រហស្បតិ៍_20-11-25", "chapterKm": "បង្រៀនបំប៉ន", "lessonTitleKm": "បង្រៀនបំប៉ន", "lessonTitleEn": "Remedial Teaching", "objectivesKm": "បង្រៀនបំប៉នសិស្សលើស្រៈ ា ិ ី", "hoursCount": 1, "semester": 1, "status": "completed", "notes": "បង្រៀនបំប៉ន"},
        {"id": "g1_kh_23", "weekNumber": 3, "subjectId": "sub_khmer", "monthKm": "វិច្ឆិកា", "dateStr": "សុក្រ_21-11-25", "chapterKm": "ស្រៈនិស្ស័យ", "lessonNumber": 12, "lessonTitleKm": "១២.មេរៀនទី២-៤ ស្រៈនិស្ស័យ ឹ", "lessonTitleEn": "12. Dependent Vowel Eu (ឹ)", "objectivesKm": "កំណត់សូរ កំណត់រូបរាង អាន និងសរសេរ ស្រៈ«ឹ»។ អានព្យាង្គ ពាក្យ និងបង្កើតល្បះផ្ទាល់មាត់ ដែលមានព្យញ្ជនៈ ក ខ ច ឆ ផ្សំជាមួយស្រៈ«ឹ»។", "hoursCount": 2, "semester": 1, "status": "completed", "pageSs": 16},
        {"id": "g1_kh_24", "weekNumber": 3, "subjectId": "sub_khmer", "monthKm": "វិច្ឆិកា", "dateStr": "សុក្រ_21-11-25", "chapterKm": "ម៉ោងបត់បែន/តេស្ត", "lessonTitleKm": "ម៉ោងបត់បែន / តេស្តប្រចាំខែ", "lessonTitleEn": "Flexible Hour / Monthly Test", "objectivesKm": "តេស្តសមត្ថភាពអាន និងសរសេរប្រចាំខែវិច្ឆិកា", "hoursCount": 1, "semester": 1, "status": "completed", "notes": "ម៉ោងបត់បែន/តេស្តប្រចាំខែ"},
        
        # សប្តាហ៍ទី៤
        {"id": "g1_kh_25", "weekNumber": 4, "subjectId": "sub_khmer", "monthKm": "វិច្ឆិកា", "dateStr": "សៅរ៍_22-11-25", "chapterKm": "ស្រៈនិស្ស័យ", "lessonNumber": 13, "lessonTitleKm": "១៣.មេរៀនទី២-៤ ស្រៈនិស្ស័យ ឺ", "lessonTitleEn": "13. Dependent Vowel Euu (ឺ)", "objectivesKm": "កំណត់សូរ កំណត់រូបរាង អាន និងសរសេរ ស្រៈ«ឺ»។ អានព្យាង្គ ពាក្យ និងបង្កើតល្បះផ្ទាល់មាត់។", "hoursCount": 2, "semester": 1, "status": "completed", "pageSs": 18},
        {"id": "g1_kh_26", "weekNumber": 4, "subjectId": "sub_khmer", "monthKm": "វិច្ឆិកា", "dateStr": "ចន្ទ_24-11-25", "chapterKm": "ស្រៈនិស្ស័យ", "lessonNumber": 14, "lessonTitleKm": "១៤.មេរៀនទី២-៤ ស្រៈនិស្ស័យ ុ", "lessonTitleEn": "14. Dependent Vowel U (ុ)", "objectivesKm": "កំណត់សូរ កំណត់រូបរាង អាន និងសរសេរ ស្រៈ«ុ»។ អានព្យាង្គ ពាក្យ និងបង្កើតល្បះផ្ទាល់មាត់។", "hoursCount": 2, "semester": 1, "status": "completed", "pageSs": 20},
        {"id": "g1_kh_27", "weekNumber": 4, "subjectId": "sub_khmer", "monthKm": "វិច្ឆិកា", "dateStr": "ចន្ទ_24-11-25", "chapterKm": "ម៉ោងបត់បែន", "lessonTitleKm": "ម៉ោងបត់បែន", "lessonTitleEn": "Flexible Hour", "objectivesKm": "ហ្វឹកហាត់សរសេរស្រៈ ុ", "hoursCount": 1, "semester": 1, "status": "completed", "notes": "ម៉ោងបត់បែន"},
        {"id": "g1_kh_28", "weekNumber": 4, "subjectId": "sub_khmer", "monthKm": "វិច្ឆិកា", "dateStr": "អង្គារ_25-11-25", "chapterKm": "ស្រៈនិស្ស័យ", "lessonNumber": 15, "lessonTitleKm": "១៥.មេរៀនទី២-៤ ស្រៈនិស្ស័យ ូ", "lessonTitleEn": "15. Dependent Vowel Oo (ូ)", "objectivesKm": "កំណត់សូរ កំណត់រូបរាង អាន និងសរសេរ ស្រៈ«ូ»។ អានព្យាង្គ ពាក្យ និងបង្កើតល្បះផ្ទាល់មាត់។", "hoursCount": 2, "semester": 1, "status": "completed", "pageSs": 22},
        {"id": "g1_kh_29", "weekNumber": 4, "subjectId": "sub_khmer", "monthKm": "វិច្ឆិកា", "dateStr": "ពុធ_26-11-25", "chapterKm": "ស្រៈនិស្ស័យ", "lessonNumber": 16, "lessonTitleKm": "១៦.មេរៀនទី២-៤ ស្រៈនិស្ស័យ ួ", "lessonTitleEn": "16. Dependent Vowel Ua (ួ)", "objectivesKm": "កំណត់សូរ កំណត់រូបរាង អាន និងសរសេរ ស្រៈ«ួ»។ អានព្យាង្គ ពាក្យ និងបង្កើតល្បះផ្ទាល់មាត់។", "hoursCount": 2, "semester": 1, "status": "completed", "pageSs": 24},
        {"id": "g1_kh_30", "weekNumber": 4, "subjectId": "sub_khmer", "monthKm": "វិច្ឆិកា", "dateStr": "ពុធ_26-11-25", "chapterKm": "ម៉ោងបត់បែន", "lessonTitleKm": "ម៉ោងបត់បែន", "lessonTitleEn": "Flexible Hour", "objectivesKm": "ហ្វឹកហាត់ផ្សំស្រៈ ួ", "hoursCount": 1, "semester": 1, "status": "completed", "notes": "ម៉ោងបត់បែន"},
        {"id": "g1_kh_31", "weekNumber": 4, "subjectId": "sub_khmer", "monthKm": "វិច្ឆិកា", "dateStr": "ព្រហស្បតិ៍_27-11-25", "chapterKm": "ប្រជុំបច្ចេកទេស", "lessonTitleKm": "ប្រជុំបច្ចេកទេស", "lessonTitleEn": "Technical Meeting", "objectivesKm": "ប្រជុំបច្ចេកទេសគ្រូបឋមសិក្សាប្រចាំខែ", "hoursCount": 0, "semester": 1, "status": "completed", "notes": "ប្រជុំបច្ចេកទេស"},
        {"id": "g1_kh_32", "weekNumber": 4, "subjectId": "sub_khmer", "monthKm": "វិច្ឆិកា", "dateStr": "សុក្រ_28-11-25", "chapterKm": "ស្រៈនិស្ស័យ", "lessonNumber": 17, "lessonTitleKm": "១៧.មេរៀនទី២-៤ ស្រៈនិស្ស័យ ើ", "lessonTitleEn": "17. Dependent Vowel Eoe (ើ)", "objectivesKm": "កំណត់សូរ កំណត់រូបរាង អាន និងសរសេរ ស្រៈ«ើ»។ អានព្យាង្គ ពាក្យ និងបង្កើតល្បះផ្ទាល់មាត់។", "hoursCount": 2, "semester": 1, "status": "completed", "pageSs": 26},
        {"id": "g1_kh_33", "weekNumber": 4, "subjectId": "sub_khmer", "monthKm": "វិច្ឆិកា", "dateStr": "សុក្រ_28-11-25", "chapterKm": "ម៉ោងបត់បែន", "lessonTitleKm": "ម៉ោងបត់បែន", "lessonTitleEn": "Flexible Hour", "objectivesKm": "ហ្វឹកហាត់អានពាក្យ ដើ ជើ", "hoursCount": 1, "semester": 1, "status": "completed", "notes": "ម៉ោងបត់បែន"},
        
        # សប្តាហ៍ទី៥
        {"id": "g1_kh_34", "weekNumber": 5, "subjectId": "sub_khmer", "monthKm": "វិច្ឆិកា", "dateStr": "សៅរ៍_29-11-25", "chapterKm": "ស្រៈនិស្ស័យ", "lessonNumber": 18, "lessonTitleKm": "១៨.មេរៀនទី២-៤ ស្រៈនិស្ស័យ ឿ", "lessonTitleEn": "18. Dependent Vowel Eua (ឿ)", "objectivesKm": "កំណត់សូរ កំណត់រូបរាង អាន និងសរសេរ ស្រៈ«ឿ»។ អានព្យាង្គ ពាក្យ និងបង្កើតល្បះផ្ទាល់មាត់។", "hoursCount": 2, "semester": 1, "status": "completed", "pageSs": 28},

        # === ខែធ្នូ (December) ===
        {"id": "g1_kh_35", "weekNumber": 5, "subjectId": "sub_khmer", "monthKm": "ធ្នូ", "dateStr": "ចន្ទ_01-12-25", "chapterKm": "ស្រៈនិស្ស័យ", "lessonNumber": 19, "lessonTitleKm": "១៩.មេរៀនទី២-៤ ស្រៈនិស្ស័យ ៀ", "lessonTitleEn": "19. Dependent Vowel Ie (ៀ)", "objectivesKm": "កំណត់សូរ កំណត់រូបរាង អាន និងសរសេរ ស្រៈ«ៀ»។ អានព្យាង្គ ពាក្យ និងបង្កើតល្បះផ្ទាល់មាត់។", "hoursCount": 2, "semester": 1, "status": "completed", "pageSs": 30},
        {"id": "g1_kh_36", "weekNumber": 5, "subjectId": "sub_khmer", "monthKm": "ធ្នូ", "dateStr": "ចន្ទ_01-12-25", "chapterKm": "ម៉ោងបត់បែន", "lessonTitleKm": "ម៉ោងបត់បែន", "lessonTitleEn": "Flexible Hour", "objectivesKm": "ពង្រឹងការអាន និងសរសេរស្រៈ ៀ", "hoursCount": 1, "semester": 1, "status": "completed", "notes": "ម៉ោងបត់បែន"},
        {"id": "g1_kh_37", "weekNumber": 6, "subjectId": "sub_khmer", "monthKm": "ធ្នូ", "dateStr": "អង្គារ_02-12-25", "chapterKm": "ស្រៈនិស្ស័យ", "lessonNumber": 20, "lessonTitleKm": "២០.មេរៀនទី២-៤ ស្រៈនិស្ស័យ េ", "lessonTitleEn": "20. Dependent Vowel E (េ)", "objectivesKm": "កំណត់សូរ កំណត់រូបរាង អាន និងសរសេរ ស្រៈ«េ»។ អានព្យាង្គ ពាក្យ និងបង្កើតល្បះផ្ទាល់មាត់។", "hoursCount": 2, "semester": 1, "status": "completed", "pageSs": 32},
        {"id": "g1_kh_38", "weekNumber": 6, "subjectId": "sub_khmer", "monthKm": "ធ្នូ", "dateStr": "ពុធ_03-12-25", "chapterKm": "ស្រៈនិស្ស័យ", "lessonNumber": 21, "lessonTitleKm": "២១.មេរៀនទី២-៤ ស្រៈនិស្ស័យ ែ", "lessonTitleEn": "21. Dependent Vowel Ae (ែ)", "objectivesKm": "កំណត់សូរ កំណត់រូបរាង អាន និងសរសេរ ស្រៈ«ែ»។ អានព្យាង្គ ពាក្យ និងបង្កើតល្បះផ្ទាល់មាត់។", "hoursCount": 2, "semester": 1, "status": "completed", "pageSs": 34},
        {"id": "g1_kh_39", "weekNumber": 6, "subjectId": "sub_khmer", "monthKm": "ធ្នូ", "dateStr": "ពុធ_03-12-25", "chapterKm": "ម៉ោងបត់បែន", "lessonTitleKm": "ម៉ោងបត់បែន", "lessonTitleEn": "Flexible Hour", "objectivesKm": "ហ្វឹកហាត់ផ្សំស្រៈ ែ", "hoursCount": 1, "semester": 1, "status": "completed", "notes": "ម៉ោងបត់បែន"},
        {"id": "g1_kh_40", "weekNumber": 6, "subjectId": "sub_khmer", "monthKm": "ធ្នូ", "dateStr": "ព្រហស្បតិ៍_04-12-25", "chapterKm": "បង្រៀនបំប៉ន", "lessonTitleKm": "បង្រៀនបំប៉ន", "lessonTitleEn": "Remedial Teaching", "objectivesKm": "បង្រៀនបំប៉នសិស្សរៀនយឺតលើស្រៈ េ ែ", "hoursCount": 1, "semester": 1, "status": "completed", "notes": "បង្រៀនបំប៉ន"},
        {"id": "g1_kh_41", "weekNumber": 6, "subjectId": "sub_khmer", "monthKm": "ធ្នូ", "dateStr": "សុក្រ_05-12-25", "chapterKm": "ស្រៈនិស្ស័យ", "lessonNumber": 22, "lessonTitleKm": "២២.មេរៀនទី២-៤ ស្រៈនិស្ស័យ ៃ", "lessonTitleEn": "22. Dependent Vowel Ai (ៃ)", "objectivesKm": "កំណត់សូរ កំណត់រូបរាង អាន និងសរសេរ ស្រៈ«ៃ»។ អានព្យាង្គ ពាក្យ និងបង្កើតល្បះផ្ទាល់មាត់។", "hoursCount": 2, "semester": 1, "status": "completed", "pageSs": 36},
        {"id": "g1_kh_42", "weekNumber": 6, "subjectId": "sub_khmer", "monthKm": "ធ្នូ", "dateStr": "សុក្រ_05-12-25", "chapterKm": "ម៉ោងបត់បែន", "lessonTitleKm": "ម៉ោងបត់បែន", "lessonTitleEn": "Flexible Hour", "objectivesKm": "ហ្វឹកហាត់សរសេរស្រៈ ៃ", "hoursCount": 1, "semester": 1, "status": "completed", "notes": "ម៉ោងបត់បែន"},
        {"id": "g1_kh_43", "weekNumber": 6, "subjectId": "sub_khmer", "monthKm": "ធ្នូ", "dateStr": "សៅរ៍_06-12-25", "chapterKm": "ស្រៈនិស្ស័យ", "lessonNumber": 23, "lessonTitleKm": "២៣.មេរៀនទី២-៤ ស្រៈនិស្ស័យ ោ", "lessonTitleEn": "23. Dependent Vowel Ao (ោ)", "objectivesKm": "កំណត់សូរ កំណត់រូបរាង អាន និងសរសេរ ស្រៈ«ោ»។ អានព្យាង្គ ពាក្យ និងបង្កើតល្បះផ្ទាល់មាត់។", "hoursCount": 2, "semester": 1, "status": "completed", "pageSs": 38},
        
        # សប្តាហ៍ទី៧
        {"id": "g1_kh_44", "weekNumber": 7, "subjectId": "sub_khmer", "monthKm": "ធ្នូ", "dateStr": "ចន្ទ_08-12-25", "chapterKm": "ស្រៈនិស្ស័យ", "lessonNumber": 24, "lessonTitleKm": "២៤.មេរៀនទី២-៤ ស្រៈនិស្ស័យ ៅ", "lessonTitleEn": "24. Dependent Vowel Au (ៅ)", "objectivesKm": "កំណត់សូរ កំណត់រូបរាង អាន និងសរសេរ ស្រៈ«ៅ»។ អានព្យាង្គ ពាក្យ និងបង្កើតល្បះផ្ទាល់មាត់។", "hoursCount": 2, "semester": 1, "status": "completed", "pageSs": 40},
        {"id": "g1_kh_45", "weekNumber": 7, "subjectId": "sub_khmer", "monthKm": "ធ្នូ", "dateStr": "ចន្ទ_08-12-25", "chapterKm": "ម៉ោងបត់បែន", "lessonTitleKm": "ម៉ោងបត់បែន", "lessonTitleEn": "Flexible Hour", "objectivesKm": "ហ្វឹកហាត់អានពាក្យ ទៅ ចៅ កៅ", "hoursCount": 1, "semester": 1, "status": "completed", "notes": "ម៉ោងបត់បែន"},
        {"id": "g1_kh_46", "weekNumber": 7, "subjectId": "sub_khmer", "monthKm": "ធ្នូ", "dateStr": "អង្គារ_09-12-25", "chapterKm": "ស្រៈនិស្ស័យ", "lessonNumber": 25, "lessonTitleKm": "២៥.មេរៀនទី២-៤ ស្រៈនិស្ស័យ ុំ", "lessonTitleEn": "25. Dependent Vowel Om (ុំ)", "objectivesKm": "កំណត់សូរ កំណត់រូបរាង អាន និងសរសេរ ស្រៈ«ុំ»។ អានព្យាង្គ ពាក្យ និងបង្កើតល្បះផ្ទាល់មាត់។", "hoursCount": 2, "semester": 1, "status": "completed", "pageSs": 42},
        {"id": "g1_kh_47", "weekNumber": 7, "subjectId": "sub_khmer", "monthKm": "ធ្នូ", "dateStr": "ពុធ_10-12-25", "chapterKm": "ស្រៈនិស្ស័យ", "lessonNumber": 26, "lessonTitleKm": "២៦.មេរៀនទី២-៤ ស្រៈនិស្ស័យ ំ", "lessonTitleEn": "26. Dependent Vowel Am (ំ)", "objectivesKm": "កំណត់សូរ កំណត់រូបរាង អាន និងសរសេរ ស្រៈ«ំ»។ អានព្យាង្គ ពាក្យ និងបង្កើតល្បះផ្ទាល់មាត់។", "hoursCount": 2, "semester": 1, "status": "completed", "pageSs": 44},
        {"id": "g1_kh_48", "weekNumber": 7, "subjectId": "sub_khmer", "monthKm": "ធ្នូ", "dateStr": "ពុធ_10-12-25", "chapterKm": "ម៉ោងបត់បែន", "lessonTitleKm": "ម៉ោងបត់បែន", "lessonTitleEn": "Flexible Hour", "objectivesKm": "ហ្វឹកហាត់ផ្សំស្រៈ ំ", "hoursCount": 1, "semester": 1, "status": "completed", "notes": "ម៉ោងបត់បែន"},
        {"id": "g1_kh_49", "weekNumber": 7, "subjectId": "sub_khmer", "monthKm": "ធ្នូ", "dateStr": "ព្រហស្បតិ៍_11-12-25", "chapterKm": "បង្រៀនបំប៉ន", "lessonTitleKm": "បង្រៀនបំប៉ន", "lessonTitleEn": "Remedial Teaching", "objectivesKm": "បង្រៀនបំប៉នសិស្សលើស្រៈ ុំ ំ", "hoursCount": 1, "semester": 1, "status": "completed", "notes": "បង្រៀនបំប៉ន"},
        {"id": "g1_kh_50", "weekNumber": 7, "subjectId": "sub_khmer", "monthKm": "ធ្នូ", "dateStr": "សុក្រ_12-12-25", "chapterKm": "ស្រៈនិស្ស័យ", "lessonNumber": 27, "lessonTitleKm": "២៧.មេរៀនទី២-៤ ស្រៈនិស្ស័យ ាំ", "lessonTitleEn": "27. Dependent Vowel Aam (ាំ)", "objectivesKm": "កំណត់សូរ កំណត់រូបរាង អាន និងសរសេរ ស្រៈ«ាំ»។ អានព្យាង្គ ពាក្យ និងបង្កើតល្បះផ្ទាល់មាត់។", "hoursCount": 2, "semester": 1, "status": "completed", "pageSs": 46},
        {"id": "g1_kh_51", "weekNumber": 7, "subjectId": "sub_khmer", "monthKm": "ធ្នូ", "dateStr": "សុក្រ_12-12-25", "chapterKm": "ម៉ោងបត់បែន", "lessonTitleKm": "ម៉ោងបត់បែន", "lessonTitleEn": "Flexible Hour", "objectivesKm": "ហ្វឹកហាត់សរសេរស្រៈ ាំ", "hoursCount": 1, "semester": 1, "status": "completed", "notes": "ម៉ោងបត់បែន"},
        {"id": "g1_kh_52", "weekNumber": 7, "subjectId": "sub_khmer", "monthKm": "ធ្នូ", "dateStr": "សៅរ៍_13-12-25", "chapterKm": "ស្រៈនិស្ស័យ", "lessonNumber": 28, "lessonTitleKm": "២៨.មេរៀនទី២-៤ ស្រៈនិស្ស័យ ះ", "lessonTitleEn": "28. Dependent Vowel Ah (ះ)", "objectivesKm": "កំណត់សូរ កំណត់រូបរាង អាន និងសរសេរ ស្រៈ«ះ»។ អានព្យាង្គ ពាក្យ និងបង្កើតល្បះផ្ទាល់មាត់។", "hoursCount": 2, "semester": 1, "status": "completed", "pageSs": 48},
        
        # សប្តាហ៍ទី៨
        {"id": "g1_kh_53", "weekNumber": 8, "subjectId": "sub_khmer", "monthKm": "ធ្នូ", "dateStr": "ចន្ទ_15-12-25", "chapterKm": "ស្រៈនិស្ស័យ", "lessonNumber": 29, "lessonTitleKm": "២៩.មេរៀនទី២-៤ ស្រៈនិស្ស័យ ុះ", "lessonTitleEn": "29. Dependent Vowel Oh (ុះ)", "objectivesKm": "កំណត់សូរ កំណត់រូបរាង អាន និងសរសេរ ស្រៈ«ុះ»។ អានព្យាង្គ ពាក្យ និងបង្កើតល្បះផ្ទាល់មាត់។", "hoursCount": 2, "semester": 1, "status": "completed", "pageSs": 50},
        {"id": "g1_kh_54", "weekNumber": 8, "subjectId": "sub_khmer", "monthKm": "ធ្នូ", "dateStr": "ចន្ទ_15-12-25", "chapterKm": "ម៉ោងបត់បែន", "lessonTitleKm": "ម៉ោងបត់បែន", "lessonTitleEn": "Flexible Hour", "objectivesKm": "ហ្វឹកហាត់ផ្សំសូរ ស្រៈ ុះ", "hoursCount": 1, "semester": 1, "status": "completed", "notes": "ម៉ោងបត់បែន"},
        {"id": "g1_kh_55", "weekNumber": 8, "subjectId": "sub_khmer", "monthKm": "ធ្នូ", "dateStr": "អង្គារ_16-12-25", "chapterKm": "ស្រៈនិស្ស័យ", "lessonNumber": 30, "lessonTitleKm": "៣០.មេរៀនទី២-៤ ស្រៈនិស្ស័យ េះ", "lessonTitleEn": "30. Dependent Vowel Eh (េះ)", "objectivesKm": "កំណត់សូរ កំណត់រូបរាង អាន និងសរសេរ ស្រៈ«េះ»។ អានព្យាង្គ ពាក្យ និងបង្កើតល្បះផ្ទាល់មាត់។", "hoursCount": 2, "semester": 1, "status": "completed", "pageSs": 52},
        {"id": "g1_kh_56", "weekNumber": 8, "subjectId": "sub_khmer", "monthKm": "ធ្នូ", "dateStr": "ពុធ_17-12-25", "chapterKm": "ស្រៈនិស្ស័យ", "lessonNumber": 31, "lessonTitleKm": "៣១.មេរៀនទី២-៤ ស្រៈនិស្ស័យ ោះ", "lessonTitleEn": "31. Dependent Vowel Aoh (ោះ)", "objectivesKm": "កំណត់សូរ កំណត់រូបរាង អាន និងសរសេរ ស្រៈ«ោះ»។ អានព្យាង្គ ពាក្យ និងបង្កើតល្បះផ្ទាល់មាត់។", "hoursCount": 2, "semester": 1, "status": "completed", "pageSs": 54},
        {"id": "g1_kh_57", "weekNumber": 8, "subjectId": "sub_khmer", "monthKm": "ធ្នូ", "dateStr": "ពុធ_17-12-25", "chapterKm": "ម៉ោងបត់បែន", "lessonTitleKm": "ម៉ោងបត់បែន", "lessonTitleEn": "Flexible Hour", "objectivesKm": "ហ្វឹកហាត់ផ្សំស្រៈ ោះ", "hoursCount": 1, "semester": 1, "status": "completed", "notes": "ម៉ោងបត់បែន"},
        {"id": "g1_kh_58", "weekNumber": 8, "subjectId": "sub_khmer", "monthKm": "ធ្នូ", "dateStr": "ព្រហស្បតិ៍_18-12-25", "chapterKm": "បង្រៀនបំប៉ន", "lessonTitleKm": "បង្រៀនបំប៉ន", "lessonTitleEn": "Remedial Teaching", "objectivesKm": "បង្រៀនបំប៉នសិស្សលើស្រៈ ុះ េះ ោះ", "hoursCount": 1, "semester": 1, "status": "completed", "notes": "បង្រៀនបំប៉ន"},
        {"id": "g1_kh_59", "weekNumber": 8, "subjectId": "sub_khmer", "monthKm": "ធ្នូ", "dateStr": "សុក្រ_19-12-25", "chapterKm": "ព្យញ្ជនៈពួកអ", "lessonNumber": 32, "lessonTitleKm": "៣២.មេរៀនទី៥ ព្យញ្ជនៈ ក", "lessonTitleEn": "32. Lesson 5: Consonant Ka (ក)", "objectivesKm": "កំណត់សូរ កំណត់រូបរាង អាន និងសរសេរ ព្យញ្ជនៈ«ក»។ អានព្យាង្គ ពាក្យ ល្បះ និងបង្កើតល្បះផ្ទាល់មាត់។ អានស្ទាត់និងយល់ន័យអត្ថបទខ្លី។", "hoursCount": 2, "semester": 1, "status": "completed", "pageSs": 57},
        {"id": "g1_kh_60", "weekNumber": 8, "subjectId": "sub_khmer", "monthKm": "ធ្នូ", "dateStr": "សុក្រ_19-12-25", "chapterKm": "ម៉ោងបត់បែន/តេស្ត", "lessonTitleKm": "ម៉ោងបត់បែន / តេស្តប្រចាំខែ", "lessonTitleEn": "Flexible Hour / Monthly Test", "objectivesKm": "តេស្តសមត្ថភាពអាន និងសរសេរប្រចាំខែធ្នូ", "hoursCount": 1, "semester": 1, "status": "completed", "notes": "ម៉ោងបត់បែន/តេស្តប្រចាំខែ"},
        {"id": "g1_kh_61", "weekNumber": 8, "subjectId": "sub_khmer", "monthKm": "ធ្នូ", "dateStr": "សៅរ៍_20-12-25", "chapterKm": "ព្យញ្ជនៈពួកអ", "lessonNumber": 33, "lessonTitleKm": "៣៣.មេរៀនទី៦ ព្យញ្ជនៈ ខ", "lessonTitleEn": "33. Lesson 6: Consonant Kha (ខ)", "objectivesKm": "កំណត់សូរ កំណត់រូបរាង អាន និងសរសេរ ព្យញ្ជនៈ«ខ»។ អានព្យាង្គ ពាក្យ ល្បះ និងបង្កើតល្បះផ្ទាល់មាត់។", "hoursCount": 2, "semester": 1, "status": "completed", "pageSs": 58},
        
        # សប្តាហ៍ទី៩
        {"id": "g1_kh_62", "weekNumber": 9, "subjectId": "sub_khmer", "monthKm": "ធ្នូ", "dateStr": "ចន្ទ_22-12-25", "chapterKm": "ព្យញ្ជនៈពួកអ", "lessonNumber": 34, "lessonTitleKm": "៣៤.មេរៀនទី៧ ព្យញ្ជនៈ ច", "lessonTitleEn": "34. Lesson 7: Consonant Cha (ច)", "objectivesKm": "កំណត់សូរ កំណត់រូបរាង អាន និងសរសេរ ព្យញ្ជនៈ«ច»។ អានព្យាង្គ ពាក្យ ល្បះ និងបង្កើតល្បះផ្ទាល់មាត់។", "hoursCount": 2, "semester": 1, "status": "completed", "pageSs": 59},
        {"id": "g1_kh_63", "weekNumber": 9, "subjectId": "sub_khmer", "monthKm": "ធ្នូ", "dateStr": "ចន្ទ_22-12-25", "chapterKm": "ម៉ោងបត់បែន", "lessonTitleKm": "ម៉ោងបត់បែន", "lessonTitleEn": "Flexible Hour", "objectivesKm": "ហ្វឹកហាត់ផ្សំ ច ជាមួយស្រៈនិស្ស័យ", "hoursCount": 1, "semester": 1, "status": "completed", "notes": "ម៉ោងបត់បែន"},
        {"id": "g1_kh_64", "weekNumber": 9, "subjectId": "sub_khmer", "monthKm": "ធ្នូ", "dateStr": "អង្គារ_23-12-25", "chapterKm": "ព្យញ្ជនៈពួកអ", "lessonNumber": 35, "lessonTitleKm": "៣៥.មេរៀនទី៨ ព្យញ្ជនៈ ឆ", "lessonTitleEn": "35. Lesson 8: Consonant Chha (ឆ)", "objectivesKm": "កំណត់សូរ កំណត់រូបរាង អាន និងសរសេរ ព្យញ្ជនៈ«ឆ»។ អានព្យាង្គ ពាក្យ ល្បះ និងបង្កើតល្បះផ្ទាល់មាត់។", "hoursCount": 2, "semester": 1, "status": "completed", "pageSs": 60},
        {"id": "g1_kh_65", "weekNumber": 9, "subjectId": "sub_khmer", "monthKm": "ធ្នូ", "dateStr": "ពុធ_24-12-25", "chapterKm": "មេរៀនសារឡើងវិញ", "lessonNumber": 36, "lessonTitleKm": "៣៦.មេរៀនសារឡើងវិញ ក ខ ច ឆ", "lessonTitleEn": "36. Review Lesson: Ka, Kha, Cha, Chha", "objectivesKm": "ផ្សំសូរ និងបំបែកសូរពាក្យដែលមានព្យញ្ជនៈ«ក ខ ច ឆ» ផ្សំស្រៈ។ អានពាក្យ ល្បះ និងបង្កើតល្បះផ្ទាល់មាត់។", "hoursCount": 2, "semester": 1, "status": "completed", "pageSs": 61},
        {"id": "g1_kh_66", "weekNumber": 9, "subjectId": "sub_khmer", "monthKm": "ធ្នូ", "dateStr": "ពុធ_24-12-25", "chapterKm": "ម៉ោងបត់បែន", "lessonTitleKm": "ម៉ោងបត់បែន", "lessonTitleEn": "Flexible Hour", "objectivesKm": "ពង្រឹងការអាន និងសរសេរ ក ខ ច ឆ", "hoursCount": 1, "semester": 1, "status": "completed", "notes": "ម៉ោងបត់បែន"},
        {"id": "g1_kh_67", "weekNumber": 9, "subjectId": "sub_khmer", "monthKm": "ធ្នូ", "dateStr": "ព្រហស្បតិ៍_25-12-25", "chapterKm": "ប្រជុំបច្ចេកទេស", "lessonTitleKm": "ប្រជុំបច្ចេកទេស", "lessonTitleEn": "Technical Meeting", "objectivesKm": "ប្រជុំបច្ចេកទេសគ្រូបឋមសិក្សាប្រចាំខែ", "hoursCount": 0, "semester": 1, "status": "completed", "notes": "ប្រជុំបច្ចេកទេស"},
        {"id": "g1_kh_68", "weekNumber": 9, "subjectId": "sub_khmer", "monthKm": "ធ្នូ", "dateStr": "សុក្រ_26-12-25", "chapterKm": "ព្យញ្ជនៈពួកអ", "lessonNumber": 37, "lessonTitleKm": "៣៧.មេរៀនទី៩ ព្យញ្ជនៈ ដ", "lessonTitleEn": "37. Lesson 9: Consonant Da (ដ)", "objectivesKm": "កំណត់សូរ កំណត់រូបរាង អាន និងសរសេរ ព្យញ្ជនៈ«ដ»។ អានព្យាង្គ ពាក្យ ល្បះ និងបង្កើតល្បះផ្ទាល់មាត់។", "hoursCount": 2, "semester": 1, "status": "completed", "pageSs": 62},
        {"id": "g1_kh_69", "weekNumber": 9, "subjectId": "sub_khmer", "monthKm": "ធ្នូ", "dateStr": "សុក្រ_26-12-25", "chapterKm": "ម៉ោងបត់បែន", "lessonTitleKm": "ម៉ោងបត់បែន", "lessonTitleEn": "Flexible Hour", "objectivesKm": "ហ្វឹកហាត់សរសេរ ដ លើក្តារឆ្នួន", "hoursCount": 1, "semester": 1, "status": "completed", "notes": "ម៉ោងបត់បែន"},
        {"id": "g1_kh_70", "weekNumber": 9, "subjectId": "sub_khmer", "monthKm": "ធ្នូ", "dateStr": "សៅរ៍_27-12-25", "chapterKm": "ព្យញ្ជនៈពួកអ", "lessonNumber": 38, "lessonTitleKm": "៣៨.មេរៀនទី១០ ព្យញ្ជនៈ ឋ", "lessonTitleEn": "38. Lesson 10: Consonant Tha (ឋ)", "objectivesKm": "កំណត់សូរ កំណត់រូបរាង អាន និងសរសេរ ព្យញ្ជនៈ«ឋ»។ អានព្យាង្គ ពាក្យ ល្បះ និងបង្កើតល្បះផ្ទាល់មាត់។", "hoursCount": 2, "semester": 1, "status": "completed", "pageSs": 63},
        
        # សប្តាហ៍ទី១០
        {"id": "g1_kh_71", "weekNumber": 10, "subjectId": "sub_khmer", "monthKm": "ធ្នូ", "dateStr": "ចន្ទ_29-12-25", "chapterKm": "ព្យញ្ជនៈពួកអ", "lessonNumber": 39, "lessonTitleKm": "៣៩.មេរៀនទី១១ ព្យញ្ជនៈ ណ", "lessonTitleEn": "39. Lesson 11: Consonant Na (ណ)", "objectivesKm": "កំណត់សូរ កំណត់រូបរាង អាន និងសរសេរ ព្យញ្ជនៈ«ណ»។ អានព្យាង្គ ពាក្យ ល្បះ និងបង្កើតល្បះផ្ទាល់មាត់។", "hoursCount": 2, "semester": 1, "status": "completed", "pageSs": 64},
        {"id": "g1_kh_72", "weekNumber": 10, "subjectId": "sub_khmer", "monthKm": "ធ្នូ", "dateStr": "ចន្ទ_29-12-25", "chapterKm": "ម៉ោងបត់បែន", "lessonTitleKm": "ម៉ោងបត់បែន", "lessonTitleEn": "Flexible Hour", "objectivesKm": "ហ្វឹកហាត់ផ្សំ ណ ជាមួយស្រៈ", "hoursCount": 1, "semester": 1, "status": "completed", "notes": "ម៉ោងបត់បែន"},
        {"id": "g1_kh_73", "weekNumber": 10, "subjectId": "sub_khmer", "monthKm": "ធ្នូ", "dateStr": "អង្គារ_30-12-25", "chapterKm": "មេរៀនសារឡើងវិញ", "lessonNumber": 40, "lessonTitleKm": "៤០.មេរៀនសារឡើងវិញ ដ ឋ ណ", "lessonTitleEn": "40. Review Lesson: Da, Tha, Na", "objectivesKm": "ផ្សំសូរ និងបំបែកសូរពាក្យដែលមានព្យញ្ជនៈ«ដ ឋ ណ» ផ្សំស្រៈ។ អានពាក្យ ល្បះ និងបង្កើតល្បះផ្ទាល់មាត់។", "hoursCount": 2, "semester": 1, "status": "completed", "pageSs": 65},
        {"id": "g1_kh_74", "weekNumber": 10, "subjectId": "sub_khmer", "monthKm": "ធ្នូ", "dateStr": "ពុធ_31-12-25", "chapterKm": "ព្យញ្ជនៈពួកអ", "lessonNumber": 41, "lessonTitleKm": "៤១.មេរៀនទី១២ ព្យញ្ជនៈ ត", "lessonTitleEn": "41. Lesson 12: Consonant Ta (ត)", "objectivesKm": "កំណត់សូរ កំណត់រូបរាង អាន និងសរសេរ ព្យញ្ជនៈ«ត»។ អានអត្ថបទខ្លី និងឆ្លើយសំណួរទាក់ទងនឹងព័ត៌មានបង្ហាញត្រង់និងបង្កប់។", "hoursCount": 2, "semester": 1, "status": "completed", "pageSs": 66},
        {"id": "g1_kh_75", "weekNumber": 10, "subjectId": "sub_khmer", "monthKm": "ធ្នូ", "dateStr": "ពុធ_31-12-25", "chapterKm": "ម៉ោងបត់បែន", "lessonTitleKm": "ម៉ោងបត់បែន", "lessonTitleEn": "Flexible Hour", "objectivesKm": "ហ្វឹកហាត់សរសេរ តា តើ ទៅ", "hoursCount": 1, "semester": 1, "status": "completed", "notes": "ម៉ោងបត់បែន"}
    ]

print("Loaded base Grade 1 lessons")
